Repository openmls/openmls, pull requests merged in 2020-12, with the labels that each got.

#230 messages refactoring
  src/codec.rs
  src/framing/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/new_from_welcome.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/schedule/mod.rs
  src/schedule/psk.rs
  src/tree/mod.rs
  tests/test_group.rs
  tests/utils/mod.rs
Labels: size/m

#225 Key Schedule Redesign
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/framing/mod.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/schedule/errors.rs
  src/schedule/mod.rs
  src/schedule/test_schedule.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_secret_tree.rs
  tests/test_group.rs
Labels: size/xl

#226 Managed group API implementation 1/?
  src/extensions/mod.rs
  src/framing/mod.rs
  src/group/errors.rs
  src/group/managed_group/callbacks.rs
  src/group/managed_group/config.rs
  src/group/managed_group/errors.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/lib.rs
  src/messages/proposals.rs
  src/prelude.rs
  src/tree/index.rs
  src/tree/mod.rs
  src/tree/node.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/test_managed_group.rs
  tests/utils/mod.rs
Labels: size/xl

#237 Harmonise some naming
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/mod.rs
  src/creds.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/extensions/ratchet_tree_extension.rs
  src/extensions/test_extensions.rs
  src/framing/mod.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/proposals.rs
  src/messages/test_proposals.rs
  src/schedule/mod.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_private_tree.rs
  src/tree/test_secret_tree.rs
  src/utils.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/test_key_packages.rs
  tests/test_managed_group.rs
  tests/utils/mod.rs
Labels: size/l

#239 Managed Group API 2/2
  src/group/managed_group/mod.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/key_packages/mod.rs
  src/messages/proposals.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/utils/mod.rs
Labels: size/s

#244 Quick fix for handshake message encryption
  src/framing/errors.rs
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/mod.rs
  src/key_packages/mod.rs
  src/prelude.rs
  src/tree/mod.rs
  src/tree/sender_ratchet.rs
  tests/test_managed_group.rs
Labels: size/xl

#240 Persistence for groups
  Cargo.toml
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/ser.rs
  src/config/mod.rs
  src/creds.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/extensions/ratchet_tree_extension.rs
  src/framing/mod.rs
  src/framing/sender.rs
  src/group/managed_group/callbacks.rs
  src/group/managed_group/config.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/ser.rs
  src/group/managed_group/test_managed_group.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_mls_group.rs
  src/group/mod.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/schedule/mod.rs
  src/tree/index.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/path_keys.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/utils.rs
  tests/test_managed_group.rs
Labels: size/l

#250 MLS PoC Delivery Service
  .github/workflows/main.yml
  Cargo.toml
  README.md
  delivery-service/ds-lib/.gitignore
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds-lib/Readme.md
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/Cargo.toml
  delivery-service/ds/README.md
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  src/group/managed_group/mod.rs
  src/prelude.rs
Labels: size/l

#256 disable macos fuzzing
  .github/workflows/main.yml
Labels: size/xs

#253 ignore PoC code for codecov
  codecov.yml
Labels: size/xs

#259 Introduce dependabot
  .github/dependabot.yml
Labels: size/s

#249 OpenMLS PoC Cli
  .github/workflows/main.yml
  Cargo.toml
  README.md
  cli/.gitignore
  cli/Cargo.toml
  cli/src/backend.rs
  cli/src/conversation.rs
  cli/src/identity.rs
  cli/src/main.rs
  cli/src/networking.rs
  cli/src/user.rs
Labels: size/l

#248 Proposals by value
  .github/workflows/main.yml
  .gitignore
  cli/src/main.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/proposal_decode.rs
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/managed_group/config.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/messages/codec.rs
  src/messages/errors.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/messages/test_proposals.rs
  src/prelude.rs
  src/tree/mod.rs
  src/tree/path_keys.rs
  src/utils.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/utils/mod.rs
Labels: size/xl

#254 Errors for OpenMLS
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  src/codec.rs
  src/config/errors.rs
  src/error.rs
  src/framing/errors.rs
  src/group/errors.rs
  src/group/managed_group/errors.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/lib.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  tests/test_encoding.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_managed_group.rs
Labels: size/l

#258 Introduce issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/mls-spec-change.md
Labels: size/s

#262 Redundant ciphertexts
  cli/src/backend.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/tree/mod.rs
  src/tree/test_resolution.rs
Labels: size/m

#266 Return optional Welcome messages
  src/group/managed_group/mod.rs
  tests/test_managed_group.rs
Labels: size/s

#268 Bump HPKE and evercrypt
  Cargo.toml
Labels: size/xs

#269 add zulip and mailing list
  README.md
Labels: size/xs

#271 add zulip link to issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/mls-spec-change.md
Labels: size/xs

#273 Version 0.3
  Cargo.toml
  README.md
Labels: size/xs

#274 finish error rewrite
  src/ciphersuite/errors.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/signable.rs
  src/codec/errors.rs
  src/codec/mod.rs
  src/config/errors.rs
  src/credentials/errors.rs
  src/credentials/mod.rs
  src/error.rs
  src/extensions/errors.rs
  src/extensions/mod.rs
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/errors.rs
  src/group/managed_group/callbacks.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/errors.rs
  src/key_packages/mod.rs
  src/lib.rs
  src/messages/errors.rs
  src/messages/test_proposals.rs
  src/prelude.rs
  src/tree/errors.rs
  src/tree/mod.rs
  src/tree/test_private_tree.rs
  src/tree/test_treemath.rs
Labels: size/l

#276 Framing refactor 1/X
  src/framing/ciphertext.rs
  src/framing/codec.rs
  src/framing/mod.rs
  src/framing/plaintext.rs
  src/framing/test_framing.rs
Labels: size/xl

#277 rewrite KeyPackageError
  src/key_packages/errors.rs
  src/key_packages/mod.rs
Labels: size/m

#272 introduce HpkeError::DecryptionError for failed hpke_open calls
  src/ciphersuite/errors.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_mls_group.rs
  src/messages/test_welcome.rs
  src/tree/errors.rs
  src/tree/mod.rs
  src/tree/test_private_tree.rs
Labels: size/m

#278 extension verification logging
  src/key_packages/codec.rs
  src/key_packages/mod.rs
Labels: size/xs

#279 windows support
  .github/workflows/benches.yml
  .github/workflows/cli.yml
  .github/workflows/ds.yml
  .github/workflows/fuzz.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  Cargo.toml
Labels: size/m

#275 Enforce proposal ordering in the ProposalQueue
  src/group/errors.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/messages/errors.rs
  src/messages/proposals.rs
  src/messages/test_proposals.rs
Labels: size/m
