Repository openmls/openmls, pull requests merged in 2020-10, with the labels that each got.

#40 gh actions
  .github/workflows/labeler.yml
  .github/workflows/main.yml
Labels: size/s

#43 use hpke versioned git
  Cargo.toml
Labels: size/xs

#38 Refactor create commit
  Cargo.toml
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/messages/proposals.rs
  src/tree/codec.rs
  src/tree/mod.rs
  src/tree/test_treemath.rs
  tests/test_group.rs
Labels: size/m

#66 tree reorgv2
  src/ciphersuite/mod.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/new_from_welcome.rs
  src/messages/mod.rs
  src/tree/codec.rs
  src/tree/hash_input.rs
  src/tree/index.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/path_keys.rs
  src/tree/private_tree.rs
  src/tree/test_path_keys.rs
  src/tree/test_private_tree.rs
  src/tree/test_util.rs
  src/tree/treemath.rs
  src/utils.rs
  tests/test_utils.rs
Labels: size/xl

#90 Fix compiler warnings
  src/framing/mod.rs
  src/key_packages/mod.rs
  src/messages/proposals.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  tests/test_group.rs
Labels: size/s

#87 Address issue 60
  src/group/mls_group/mod.rs
  src/schedule.rs
Labels: size/xs

#89 Use the same tree for Handshake and Application secrets
  src/framing/mod.rs
  src/group/errors.rs
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/schedule.rs
  src/tree/astree.rs
  src/tree/codec.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_astree.rs
  src/tree/test_secret_tree.rs
Labels: size/xl

#97 Extensions 2/?
  src/codec.rs
  src/config.rs
  src/errors.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/extensions/ratchet_tree_extension.rs
  src/extensions/test_extensions.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/messages/mod.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/utils.rs
  tests/test_config.rs
  tests/test_key_packages.rs
Labels: size/l

#109 Fix cargo fmt
  src/group/errors.rs
Labels: size/xs

#112 CI update
  .github/workflows/main.yml
Labels: size/s

#110 engineering and contributing guidelines
  CONTRIBUTING.md
Labels: size/m

#102 fix tree math
  src/group/mls_group/create_commit.rs
  src/group/mls_group/new_from_welcome.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  src/tree/test_treemath.rs
  src/tree/treemath.rs
Labels: size/m

#116 globally rename 'confirmation' to 'confirmation_tag'
  src/framing/mod.rs
  src/group/mls_group/apply_commit.rs
  tests/test_group.rs
Labels: size/s

#105 Change API to enforce always MLSCiphertext
  src/group/mls_group/api.rs
  src/group/mls_group/mod.rs
  tests/test_framing.rs
Labels: size/s

#107 Make group context optional for MLSPlaintextTBS
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/mls_group/apply_commit.rs
Labels: size/m

#118 Don't allow cloning private hpke keys
  src/ciphersuite/mod.rs
  src/group/errors.rs
  src/group/managed_group.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/key_packages/mod.rs
  src/messages/proposals.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/path_keys.rs
  src/tree/private_tree.rs
Labels: size/m

#126 Fix clippy warnings
  src/ciphersuite/mod.rs
  src/codec.rs
  src/config.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/group/errors.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
Labels: size/s

#128 Global config
  Cargo.toml
  src/ciphersuite/mod.rs
  src/config.rs
  src/extensions/capabilities_extension.rs
  src/extensions/mod.rs
  src/extensions/test_extensions.rs
  tests/config.json
  tests/test_config.rs
Labels: size/m

#125 Update BasicCredential
  src/creds.rs
Labels: size/s

#120 Konrad/x509 field
  benches/benchmark.rs
  src/creds.rs
  src/framing/test_framing.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/tree/test_treemath.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/s

#132 welcome messages & ciphersuite cleanup
  benches/benchmark.rs
  src/ciphersuite/mod.rs
  src/config.rs
  src/creds.rs
  src/framing/test_framing.rs
  src/group/managed_group.rs
  src/group/mls_group/api.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/messages/test_welcome.rs
  src/tree/mod.rs
  src/tree/test_treemath.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m

#127 Enable Commit to cover new proposal types
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/tree/mod.rs
  src/tree/test_treemath.rs
Labels: size/l

#136 bump evercrypt and enable arm on travis
  .travis.yml
  Cargo.toml
Labels: size/s

#123 key package id extensions
  src/codec.rs
  src/creds.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/mod.rs
  src/extensions/test_extensions.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/tree/mod.rs
Labels: size/m

#138 Remove interim_transcript_hash from GroupInfo
  src/framing/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/messages/mod.rs
  src/messages/test_welcome.rs
Labels: size/s

#139 use hpke keys
  Cargo.toml
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/creds.rs
  src/group/mls_group/create_commit.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/test_welcome.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/test_path_keys.rs
  src/tree/test_private_tree.rs
Labels: size/m

#152 Change Api function names for compliance with the Naming Guidelines
  src/framing/mod.rs
  src/group/managed_group.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
Labels: size/s

#155 init fuzzing infrastructure
  fuzz/.gitignore
  fuzz/Cargo.toml
  fuzz/fuzz_targets/decode_key_package_target.rs
  fuzz/fuzz_targets/welcome_fuzz_decode_target.rs
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/codec.rs
  src/errors.rs
Labels: size/m

#158 Some leaf index refactoring
  src/group/managed_group.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/tree/index.rs
  src/tree/mod.rs
Labels: size/s

#156 Remove Identity in favor of CredentialBundle
  benches/benchmark.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/signable.rs
  src/creds.rs
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/mls_group/api.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/tree/mod.rs
  src/tree/test_treemath.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m

#168 bump hpke and evercrypt version
  Cargo.toml
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/key_packages/mod.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
Labels: size/s

#144 Konrad/reuse guard
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/framing/mod.rs
  src/group/mls_group/mod.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_secret_tree.rs
  tests/test_framing.rs
Labels: size/m

#157 Re-enable group tests 1/?
  src/ciphersuite/mod.rs
  src/config.rs
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/framing/mod.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/test_private_tree.rs
  src/tree/test_treemath.rs
  src/tree/treemath.rs
  src/utils.rs
  tests/test_group.rs
Labels: size/l

#173 ciphersuites cleanup: Signature keys
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/creds.rs
  src/framing/test_framing.rs
  src/group/mls_group/create_commit.rs
  tests/test_key_packages.rs
Labels: size/m

#179 adapt to HPKE changes
  src/ciphersuite/test_ciphersuite.rs
  src/messages/test_welcome.rs
Labels: size/xs

#178 misc cleanup naming
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/group/managed_group.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/lib.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/utils.rs
  src/validator.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m
