Repository openmls/openmls, pull requests merged in 2020-11, with the labels that each got.

#180 Extend HPKE test
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
Labels: size/s

#183 Renaming
  Cargo.toml
  LICENSE
  README.md
  benches/benchmark.rs
  fuzz/Cargo.toml
  fuzz/fuzz_targets/decode_key_package_target.rs
  fuzz/fuzz_targets/welcome_fuzz_decode_target.rs
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/codec.rs
  src/creds.rs
  src/errors.rs
  src/extensions/mod.rs
  src/extensions/test_extensions.rs
  src/framing/mod.rs
  src/framing/test_framing.rs
  src/group/errors.rs
  src/group/managed_group.rs
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/lib.rs
  src/messages/mod.rs
  src/schedule.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  src/tree/treemath.rs
  src/utils.rs
  tests/test_config.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/xl

#174 Extensions: Capabilities, Lifetimes & Ratchet Tree
  benches/benchmark.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/group/errors.rs
  src/group/managed_group.rs
  src/group/mls_group/api.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/tree/test_treemath.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m

#184 Introduce prelude
  benches/benchmark.rs
  src/lib.rs
  src/messages/mod.rs
  src/prelude.rs
  src/validator.rs
  tests/test_config.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m

#177 Re-enable group tests 2/?
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/group/errors.rs
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/messages/test_proposals.rs
  src/tree/index.rs
  src/tree/mod.rs
  src/tree/path_keys.rs
  src/tree/private_tree.rs
  src/tree/test_path_keys.rs
  src/tree/test_private_tree.rs
  tests/test_group.rs
Labels: size/l

#188 gh action for deploying rust docs
  .github/workflows/gh-pages.yml
Labels: size/s

#190 Only keep ARM on linux for Travis CI
  .travis.yml
Labels: size/xs

#191 run CI on main
  .github/workflows/gh-pages.yml
  .github/workflows/main.yml
Labels: size/xs

#193 Point Travis CI to main in README
  README.md
Labels: size/xs

#195 Use static ciphersuite references from the config.
  Cargo.toml
  benches/benchmark.rs
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/config.rs
  src/creds.rs
  src/extensions/capabilities_extension.rs
  src/framing/test_framing.rs
  src/group/errors.rs
  src/group/managed_group.rs
  src/group/mls_group/api.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/codec.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/messages/test_proposals.rs
  src/messages/test_welcome.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_private_tree.rs
  src/tree/test_secret_tree.rs
  src/tree/test_treemath.rs
  tests/test_config.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
Labels: size/m

#170 Change apply_commit to take a reference instead of the Vector of KeyPackageBundles object
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/tree/mod.rs
  tests/test_group.rs
Labels: size/s

#197 Cover all ciphersuites in tests
  README.md
  benches/benchmark.rs
  src/ciphersuite/test_ciphersuite.rs
  src/framing/test_framing.rs
  src/key_packages/test_key_packages.rs
  src/tree/test_private_tree.rs
  src/tree/test_secret_tree.rs
  src/tree/test_treemath.rs
  tests/test_framing.rs
  tests/test_group.rs
Labels: size/xl

#198 Add utilities to quickly generate test setups
  src/group/mls_group/mod.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/messages/mod.rs
  src/prelude.rs
  tests/test_framing.rs
  tests/test_utils.rs
  tests/utils/mod.rs
Labels: size/m

#199 Don't cache on CI
  .github/workflows/main.yml
Labels: size/s

#200 Update criterion and hpke dependencies
  Cargo.toml
Labels: size/xs

#201 Add metadata to Cargo.toml
  Cargo.toml
  README.md
Labels: size/xs

#176 Introduce a Secrets type and some Ciphersuite refactoring
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/framing/mod.rs
  src/group/mls_group/api.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/messages/mod.rs
  src/messages/test_welcome.rs
  src/schedule.rs
  src/tree/codec.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_secret_tree.rs
Labels: size/l

#204 Community project 1/?
  CODEOWNERS
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: size/m

#208 Update README.md
  README.md
Labels: size/xs

#210 fuzzing ci target
  .github/workflows/main.yml
  fuzz/Cargo.toml
  fuzz/fuzz_targets/key_package_decode.rs
  fuzz/fuzz_targets/welcome_decode.rs
  src/codec.rs
  src/errors.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/parent_hash_extension.rs
  src/extensions/ratchet_tree_extension.rs
  src/prelude.rs
Labels: size/s

#209 Add logging example
  Cargo.toml
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/codec.rs
  src/config.rs
  src/creds.rs
  src/errors.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  tests/test_framing.rs
  tests/test_group.rs
Labels: size/m

#203 Add encoding/decoding tests for MLSPlaintexts, MLSCiphertexts and Welcome messages
  src/codec.rs
  src/errors.rs
  src/extensions/mod.rs
  src/framing/mod.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/tree/codec.rs
  src/tree/node.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/test_key_packages.rs
  tests/utils/mod.rs
Labels: size/l

#211 Managed group API
  src/group/managed_group.rs
  src/group/managed_group/mod.rs
  src/prelude.rs
Labels: size/m

#212 Fuzzing targets for MLSCiphertext and MLSPlaintext decode
  .github/workflows/main.yml
  fuzz/Cargo.toml
  fuzz/fuzz_targets/mls_ciphertext_decode.rs
  fuzz/fuzz_targets/mls_plaintext_decode.rs
  src/framing/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/tree/codec.rs
  src/tree/node.rs
  tests/test_encoding.rs
  tests/utils/mod.rs
Labels: size/m, tests

#217 Cleanup
  README.md
  rustfmt.toml
  src/ciphersuite/mod.rs
  src/config.rs
  src/errors.rs
  src/extensions/capabilities_extension.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/extensions/test_extensions.rs
  src/framing/sender.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/messages/proposals.rs
  src/messages/test_proposals.rs
  src/tree/hash_input.rs
  src/tree/mod.rs
  src/tree/path_keys.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/test_secret_tree.rs
  tests/test_config.rs
  tests/test_framing.rs
  tests/test_group.rs
  tests/test_key_packages.rs
  tests/utils/mod.rs
Labels: size/m

#216 unified error handling 1/2
  src/ciphersuite/ciphersuites.rs
  src/ciphersuite/errors.rs
  src/ciphersuite/mod.rs
  src/codec.rs
  src/config/errors.rs
  src/config/mod.rs
  src/creds.rs
  src/errors.rs
  src/extensions/capabilities_extension.rs
  src/extensions/errors.rs
  src/extensions/key_package_id_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/mod.rs
  src/extensions/parent_hash_extension.rs
  src/extensions/ratchet_tree_extension.rs
  src/framing/errors.rs
  src/framing/mod.rs
  src/framing/sender.rs
  src/group/errors.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/api.rs
  src/group/mls_group/mod.rs
  src/group/mod.rs
  src/key_packages/errors.rs
  src/key_packages/mod.rs
  src/lib.rs
  src/prelude.rs
  src/tree/mod.rs
  src/utils.rs
Labels: size/xl

#223 Update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#218 Integration test for managed group API
  src/framing/sender.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/key_packages/mod.rs
  src/prelude.rs
  src/tree/mod.rs
  tests/test_managed_group.rs
Labels: size/l

#222 Improve FS by dropping the encryption_secret after use
  src/framing/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/schedule/errors.rs
  src/schedule/mod.rs
  src/schedule/test_schedule.rs
  src/tree/secret_tree.rs
  src/tree/test_secret_tree.rs
Labels: size/m

#220 Add constants in the Config for the Lifetime of KeyPackages
  src/config/mod.rs
  src/extensions/life_time_extension.rs
  src/extensions/test_extensions.rs
  src/key_packages/mod.rs
  tests/test_config.rs
Labels: size/s

#227 add code coverage
  .github/workflows/coverage.yml
Labels: size/s, tests

#229 Add codecov badge
  README.md
Labels: size/xs
