Repository openmls/openmls, pull requests merged in 2021-11, with the labels that each got.

#523 Enable RatchetTreeExtensions in the CLI client
  cli/README.md
  cli/src/user.rs
Labels: bug, size/s

#522 Validation & inspectable proposals
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/ciphersuite/signable.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/ser.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/managed_group/validation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/proposals.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/messages.rs
  openmls/src/tree/mod.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/xl

#427 Add a binary tree trait and implementation
  .github/workflows/tests.yml
  openmls/src/binary_tree/array_representation.rs
  openmls/src/binary_tree/kat_treemath.rs
  openmls/src/binary_tree/mod.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/binary_tree/treemath.rs
  openmls/src/lib.rs
Labels: size/xl

#529 arm ci
  .drone.yml
  README.md
Labels: size/s

#534 Validation follow-up
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/application.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/events.rs
  openmls/src/group/managed_group/membership.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/ser.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/managed_group/updates.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/create_commit_params.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/proposals.rs
  openmls/src/group/mls_group/test_create_commit_params.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/tree/mod.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/test_managed_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/xl

#521 Evercrypt provider
  README.md
  evercrypt_backend/Cargo.toml
  evercrypt_backend/Readme.md
  evercrypt_backend/src/lib.rs
  evercrypt_backend/src/provider.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/mod.rs
  openmls/tests/test_group.rs
  openmls/tests/test_managed_group.rs
  openmls_rust_crypto/Readme.md
  rust_crypto/Cargo.toml
  rust_crypto/src/lib.rs
  traits/Readme.md
  traits/src/types.rs
Labels: size/xl

#546 Fixes for clippy errors and warnings
  cli/src/user.rs
  evercrypt_backend/src/provider.rs
  interop_client/src/main.rs
  memory_keystore/src/lib.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/tests/test_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/m

#535 Fix treemath for 32bit platforms
  openmls/src/tree/treemath.rs
Labels: size/xs

#547 Cascaded kdf
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
  openmls/test_vectors/kat_key_schedule_openmls.json
Labels: size/xl

#552 Introduce required_capabilities extension
  openmls/src/extensions/mod.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/messages/proposals.rs
Labels: size/m

#555 Followup clippy fixes
  openmls/src/extensions/required_capabilities.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
Labels: size/s

#545 Introduce type system for validation
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/message.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/validation.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/messages.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
Labels: size/l

#557 Create CredentialBundle from existing keys
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/credentials/tests.rs
Labels: size/s

#560 Start validation tests
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/validation.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_validation.rs
Labels: size/m

#564 Implement & document more validation checks
  openmls/src/ciphersuite/signature.rs
  openmls/src/framing/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/validation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/process.rs
  openmls/src/group/mls_group/proposals.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/validation.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/tree/mod.rs
Labels: size/l

#572 Use tls_codec 0.2.0-pre.2
  cli/Cargo.toml
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/Cargo.toml
  evercrypt_backend/Cargo.toml
  interop_client/Cargo.toml
  openmls/Cargo.toml
  openmls/fuzz/Cargo.toml
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/key_package_id_extension.rs
  openmls/src/extensions/life_time_extension.rs
  openmls/src/extensions/parent_hash_extension.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/sender.rs
  openmls/src/group/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/codec.rs
  openmls/src/schedule/mod.rs
  openmls/src/tree/index.rs
  openmls/src/tree/mod.rs
  openmls/src/tree/node.rs
  openmls/src/tree/secret_tree.rs
  rust_crypto/Cargo.toml
  traits/Cargo.toml
  traits/src/types.rs
Labels: size/s

#567 Group context extension proposals
  cli/src/user.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/ciphersuite/ciphersuites.rs
  openmls/src/config/errors.rs
  openmls/src/config/mod.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/managed_group/config.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/proposals.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/test_vectors/kat_messages.json
  openmls/tests/test_group.rs
  openmls/tests/utils/mls_utils/mod.rs
  test_macros/src/lib.rs
Labels: size/xl

#583 proposal extensibility testvectors
  openmls/test_vectors/kat_encryption_openmls.json
  openmls/test_vectors/kat_messages.json
  openmls/test_vectors/kat_tree_kem_openmls.json
Labels: size/xl

#586 Fix deprecated API call in RustCrypto
  rust_crypto/src/lib.rs
Labels: size/xs

#571 Continue validation tests
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/tests/test_validation.rs
Labels: size/l

#589 Update codecov.yml to avoid failing all the time
  codecov.yml
Labels: size/xs
