Repository openmls/openmls, pull requests merged in 2021-02, with the labels that each got.

#324 KeyPackage constructor check for mismatch
  src/credentials/mod.rs
  src/key_packages/errors.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
Labels: size/s

#327 Export PublicGroupState
  src/ciphersuite/signable.rs
  src/credentials/errors.rs
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/group/codec.rs
  src/group/mls_group/mod.rs
  src/key_packages/mod.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/messages/test_pgs.rs
  src/schedule/mod.rs
  src/test_util/mod.rs
  src/tree/hashes.rs
  src/tree/kat_encryption.rs
  src/tree/kat_treemath.rs
  src/tree/test_treemath.rs
  tests/test_interop_scenarios.rs
  tls-codec-derive/tests/decode.rs
  tls-codec/src/lib.rs
Labels: size/m

#331 Fix remover bug
  src/group/managed_group/callbacks.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/test_managed_group.rs
Labels: size/m

#330 key schedule reorg
  .github/workflows/tests.yml
  Cargo.toml
  src/ciphersuite/mod.rs
  src/framing/ciphertext.rs
  src/group/errors.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_mls_group.rs
  src/group/mod.rs
  src/schedule/errors.rs
  src/schedule/mod.rs
  src/tree/kat_encryption.rs
  src/tree/kat_treemath.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/utils.rs
Labels: size/l

#336 key schedule test vectors
  src/schedule/kat_key_schedule.rs
  src/schedule/mod.rs
  src/tree/kat_encryption.rs
  test_vectors/kat_key_schedule_openmls.json
Labels: size/xl

#338 transcript test vectors
  src/group/mls_group/mod.rs
  src/group/mod.rs
  src/group/tests/kat_transcripts.rs
  src/group/tests/mod.rs
  src/schedule/mod.rs
  test_vectors/kat_transcripts.json
Labels: size/xl

#339 misc cleanup
  .gitignore
  src/ciphersuite/codec.rs
  src/group/managed_group/callbacks.rs
  src/group/mls_group/mod.rs
  src/messages/mod.rs
  src/tree/index.rs
  src/utils.rs
  test_macros/src/lib.rs
  tests/test_managed_group.rs
  tests/utils/managed_utils/default_callbacks.rs
  tls-codec-derive/src/lib.rs
Labels: size/s

#340 drop old binary test vectors
  src/tree/test_treemath.rs
  test_vectors/key_schedule.bin
  test_vectors/messages.bin
  test_vectors/resolution.bin
  test_vectors/tree_math.bin
Labels: size/s

#341 Make error enums publicly visible
  src/config/mod.rs
  src/extensions/mod.rs
  src/framing/mod.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/schedule/mod.rs
  src/tree/mod.rs
Labels: size/s

#342 misc unit test cleanup
  src/framing/mod.rs
  src/group/mls_group/create_commit.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/messages/tests/mod.rs
  src/messages/tests/test_codec.rs
  src/messages/tests/test_pgs.rs
  src/messages/tests/test_proposals.rs
  src/messages/tests/test_welcome.rs
  src/tree/mod.rs
  src/tree/tests/kat_encryption.rs
  src/tree/tests/kat_treemath.rs
  src/tree/tests/mod.rs
  src/tree/tests/test_hashes.rs
  src/tree/tests/test_index.rs
  src/tree/tests/test_path_keys.rs
  src/tree/tests/test_private_tree.rs
  src/tree/tests/test_resolution.rs
  src/tree/tests/test_secret_tree.rs
  src/tree/tests/test_treemath.rs
  src/tree/tests/test_util.rs
  src/tree/treemath.rs
  test_vectors/crypto.bin
Labels: size/m

#343 Initial PSK PR
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  src/framing/test_framing.rs
  src/group/errors.rs
  src/group/managed_group/config.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/resumption.rs
  src/group/managed_group/ser.rs
  src/group/managed_group/test_managed_group.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_mls_group.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/messages/proposals.rs
  src/messages/tests/test_codec.rs
  src/messages/tests/test_pgs.rs
  src/prelude.rs
  src/schedule/codec.rs
  src/schedule/errors.rs
  src/schedule/mod.rs
  src/schedule/psk.rs
  src/tree/mod.rs
  src/tree/tests/kat_encryption.rs
  test_vectors/.gitignore
  tests/test_decryption_key_index.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/test_interop_scenarios.rs
  tests/test_managed_api.rs
  tests/test_managed_group.rs
  tests/utils/mls_utils/mod.rs
Labels: size/l

#352 Fix doc tests
  src/schedule/psk.rs
Labels: size/xs

#351 Reformat comments one last time and remove formatting rule
  rustfmt.toml
  src/group/managed_group/mod.rs
  src/group/managed_group/resumption.rs
  src/group/mls_group/mod.rs
  src/schedule/psk.rs
Labels: size/s

#353 bump HPKE to v1
  Cargo.toml
  test_vectors/kat_key_schedule_openmls.json
  tls-codec/Cargo.toml
Labels: size/xl
