Repository openmls/openmls, pull requests merged in 2021-03, with the labels that each got.

#349 Use new stuff from Rust 1.50
  src/schedule/mod.rs
Labels: size/xs

#366 Add rustc minimum version to readme
  README.md
Labels: size/xs

#365 Fix Windows build
  Cargo.toml
  tls-codec/Cargo.toml
Labels: size/xs

#350 Enable ratchet tree extensions for MlsGroup
  src/extensions/ratchet_tree_extension.rs
  src/extensions/test_extensions.rs
  src/framing/test_framing.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_duplicate_extension.rs
  src/messages/mod.rs
  src/messages/tests/test_proposals.rs
Labels: size/m

#361 Return events directly in ManagedGroup
  src/group/managed_group/callbacks.rs
  src/group/managed_group/events.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/test_managed_group.rs
  src/prelude.rs
  tests/test_decryption_key_index.rs
  tests/test_interop_scenarios.rs
  tests/test_managed_api.rs
  tests/test_managed_group.rs
  tests/utils/managed_utils/default_callbacks.rs
  tests/utils/managed_utils/mod.rs
Labels: size/l

#374 misc: make clippy happy
  src/extensions/mod.rs
  src/schedule/mod.rs
  src/tree/mod.rs
  src/tree/node.rs
Labels: size/s

#360 Allow context as input for exported secret
  src/group/managed_group/test_managed_group.rs
Labels: size/s
