Repository openmls/openmls, pull requests merged in 2021-10, with the labels that each got.

#465 Native Rust Crypto Provider
  .github/workflows/release.yml
  .github/workflows/tests.yml
  README.md
  openmls/Cargo.toml
  openmls/src/ciphersuite/ciphersuites.rs
  openmls/src/ciphersuite/crypto.rs
  openmls/src/ciphersuite/crypto/evercrypt_provider.rs
  openmls/src/ciphersuite/crypto/rust_crypto_provider.rs
  openmls/src/ciphersuite/errors.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/rand.rs
  openmls/src/config/errors.rs
  openmls/src/credentials/mod.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/psk.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/utils.rs
  openmls/test_vectors/kat_key_schedule_openmls.json
  openmls/test_vectors/kat_messages.json
  openmls/test_vectors/kat_transcripts.json
  openmls/test_vectors/kat_tree_kem_openmls.json
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/xl

#472 don't use all-features when building gh-pages
  .github/workflows/gh-pages.yml
Labels: size/xs

#444 Enable Managed API to process VerifiableMlsPlaintext
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/test_utils/test_framework/messages.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_managed_group.rs
Labels: size/m

#452 DER encode ECDSA signatures
  openmls/Cargo.toml
  openmls/src/ciphersuite/crypto/evercrypt_provider.rs
  openmls/src/ciphersuite/errors.rs
  openmls/src/ciphersuite/signable.rs
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/credentials/errors.rs
Labels: mls-spec change, size/l

#458 Fix clippy warnings
  cli/src/backend.rs
  cli/src/main.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/main.rs
  openmls/src/credentials/codec.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/key_store/test_key_store.rs
  openmls/src/messages/errors.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_framing.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/m
