Repository openmls/openmls, pull requests merged in 2021-07, with the labels that each got.

#441 update readme badges
  README.md
Labels: size/xs

#439 Pull testing framework into OpenMLS crate
  openmls/Cargo.toml
  openmls/src/ciphersuite/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/mod.rs
  openmls/src/key_store/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/mod.rs
  openmls/src/tree/tests/kat_encryption.rs
  openmls/src/tree/tests/kat_tree_kem.rs
  openmls/src/tree/tests/kat_treemath.rs
  openmls/src/tree/tests/mod.rs
  openmls/src/utils.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_tree_kem_kat.rs
  test_utils/Cargo.toml
Labels: size/l

#446 Rename add only commit to partial commit
  openmls/src/schedule/mod.rs
Labels: mls-spec change, size/xs

#443 Fix possible circumvention of verification type structure
  openmls/src/ciphersuite/signable.rs
  openmls/src/framing/plaintext.rs
Labels: size/s

#449 Re-organize tests and kats
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/tests.rs
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/ciphersuite/tests/test_secrets.rs
  openmls/src/group/tests/mod.rs
  openmls/src/tree/mod.rs
  openmls/src/tree/tests/mod.rs
  openmls/src/tree/tests_and_kats.rs
  openmls/src/tree/tests_and_kats/kats.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/kats/kat_treemath.rs
  openmls/src/tree/tests_and_kats/unit_tests.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_hashes.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_index.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_path_keys.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_treemath.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_util.rs
Labels: cleanup, size/s
