Repository openmls/openmls, pull requests merged in 2021-01, with the labels that each got.

#281 Throw an error when trying to add or remove members with an empty input
  src/group/managed_group/errors.rs
  src/group/managed_group/mod.rs
  tests/test_managed_group.rs
Labels: bug, size/s

#298 Fix CI: Forcing CI to always checkout the HEAD commit
  .github/workflows/benches.yml
  .github/workflows/cli.yml
  .github/workflows/ds.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: size/s

#306 actually check key_package_hash
  src/messages/test_welcome.rs
Labels: size/xs

#309 Move the test utils for mls_group to a subdirectory of `tests/utils`
  tests/test_encoding.rs
  tests/test_framing.rs
  tests/utils/mls_utils/mod.rs
  tests/utils/mod.rs
Labels: size/l, tests

#299 Test vector generation and testing - TreeMath and Encryption
  .github/workflows/tests.yml
  Cargo.toml
  src/ciphersuite/mod.rs
  src/framing/ciphertext.rs
  src/group/mls_group/mod.rs
  src/lib.rs
  src/schedule/mod.rs
  src/test_util/mod.rs
  src/tree/kat_encryption.rs
  src/tree/kat_treemath.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  src/tree/test_treemath.rs
  src/tree/treemath.rs
  src/utils.rs
  test_vectors/kat_encryption_openmls.json
  test_vectors/kat_treemath_openmls.json
Labels: size/xl

#308 Introduce a test framework for the managed group API
  .github/workflows/coverage.yml
  src/lib.rs
  tests/test_managed_api.rs
  tests/utils/managed_utils/client.rs
  tests/utils/managed_utils/default_callbacks.rs
  tests/utils/managed_utils/errors.rs
  tests/utils/managed_utils/mod.rs
  tests/utils/mls_utils/mod.rs
  tests/utils/mod.rs
Labels: size/xl, tests

#317 Move tree hashing code
  src/tree/hashes.rs
  src/tree/mod.rs
Labels: size/m

#315 Proc macro to test all ciphersuites
  Cargo.toml
  test_macros/Cargo.toml
  test_macros/src/lib.rs
  tests/test_key_packages.rs
Labels: size/m

#305 Compute the correct index to retrieve the decryption key from
  src/group/mls_group/new_from_welcome.rs
  src/tree/mod.rs
  tests/test_decryption_key_index.rs
  tests/utils/managed_utils/mod.rs
Labels: bug, size/m

#318 TLS codec crate & derive
  Cargo.toml
  tls-codec-derive/Cargo.toml
  tls-codec-derive/src/lib.rs
  tls-codec-derive/tests/decode.rs
  tls-codec-derive/tests/encode.rs
  tls-codec/Cargo.toml
  tls-codec/src/arrays.rs
  tls-codec/src/hpke.rs
  tls-codec/src/lib.rs
  tls-codec/src/primitives.rs
  tls-codec/src/tls_vec.rs
  tls-codec/tests/decode.rs
  tls-codec/tests/encode.rs
Labels: size/l

#312 Introduce tests corresponding to the Interop test scenarios
  tests/test_interop_scenarios.rs
  tests/utils/managed_utils/default_callbacks.rs
  tests/utils/managed_utils/mod.rs
Labels: size/m, tests

#322 Add ctest_panic macro
  test_macros/src/lib.rs
Labels: size/s

#320 Make results of sign/verify consistent
  src/ciphersuite/mod.rs
  src/ciphersuite/signable.rs
  src/ciphersuite/test_ciphersuite.rs
  src/credentials/errors.rs
  src/credentials/mod.rs
  src/framing/errors.rs
  src/framing/plaintext.rs
  src/group/errors.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/tree/hashes.rs
  src/tree/test_hashes.rs
  test_macros/src/lib.rs
  tests/utils/managed_utils/mod.rs
Labels: size/m

#325 Make composite types 2^32 and make 0 invalid for enums
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/framing/test_framing.rs
  src/group/codec.rs
  src/group/group_context.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mod.rs
  src/key_packages/mod.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/messages/test_proposals.rs
  src/tree/codec.rs
Labels: size/s

#321 Consolidate direct_path functions in TreeMath
  src/group/mls_group/new_from_welcome.rs
  src/schedule/mod.rs
  src/tree/mod.rs
  src/tree/secret_tree.rs
  src/tree/test_treemath.rs
  src/tree/treemath.rs
Labels: size/m
