Repository openmls/openmls, pull requests merged in 2021-05, with the labels that each got.

#392 Slight refactoring of path secrets in preparation of TreeKEM kat merge
  src/group/managed_group/mod.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/new_from_welcome.rs
  src/messages/mod.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
Labels: size/m

#396 Some refactoring and simplification of the RatchetTree
  src/ciphersuite/mod.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/key_packages/mod.rs
  src/tree/mod.rs
  src/tree/tests/test_hashes.rs
  src/tree/tests/test_resolution.rs
  src/tree/tests/test_treemath.rs
Labels: size/m

#398 check that tree math input is valid
  src/tree/tests/test_treemath.rs
  src/tree/treemath.rs
Labels: size/m

#397 Refactor Managed API to accept and return individual messages
  src/framing/plaintext.rs
  src/group/managed_group/errors.rs
  src/group/managed_group/events.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/test_managed_group.rs
  tests/test_managed_group.rs
  tests/utils/managed_utils/client.rs
  tests/utils/managed_utils/mod.rs
Labels: size/l

#400 Add messages test vector
  src/extensions/capabilities_extension.rs
  src/extensions/life_time_extension.rs
  src/extensions/test_extensions.rs
  src/group/tests/kat_messages.rs
  src/group/tests/kat_transcripts.rs
  src/group/tests/mod.rs
  src/messages/mod.rs
  src/schedule/mod.rs
  src/utils.rs
  test_vectors/kat_messages.json
Labels: size/xl, test-vectors

#399 Fix bug in path_secrets function and include TreeKEM test vector
  Cargo.toml
  src/ciphersuite/mod.rs
  src/extensions/mod.rs
  src/extensions/ratchet_tree_extension.rs
  src/key_packages/mod.rs
  src/key_store/mod.rs
  src/lib.rs
  src/messages/mod.rs
  src/tree/codec.rs
  src/tree/mod.rs
  src/tree/tests/kat_tree_kem.rs
  src/tree/tests/mod.rs
  test_vectors/kat_tree_kem_openmls.json
  tests/test_tree_kem_kat.rs
Labels: size/xl

#406 Fix clippy warnings
  src/key_store/test_key_store.rs
  test_macros/tests/tests.rs
  tests/test_tree_kem_kat.rs
Labels: size/s

#407 Minor fixes to message formats and mlspp test vectors
  src/extensions/mod.rs
  src/extensions/test_extensions.rs
  src/framing/codec.rs
  src/framing/plaintext.rs
  src/framing/test_framing.rs
  src/group/mls_group/apply_commit.rs
  src/group/tests/kat_transcripts.rs
  src/schedule/kat_key_schedule.rs
  src/tree/tests/kat_encryption.rs
  src/tree/tests/kat_treemath.rs
  test_vectors/kat_messages.json
  test_vectors/kat_transcripts.json
  test_vectors/kat_tree_kem_openmls.json
  test_vectors/mlspp/mlspp_encryption_1_10.json
  test_vectors/mlspp/mlspp_encryption_2_10.json
  test_vectors/mlspp/mlspp_encryption_3_10.json
  test_vectors/mlspp/mlspp_key_schedule_1.json
  test_vectors/mlspp/mlspp_key_schedule_2.json
  test_vectors/mlspp/mlspp_key_schedule_3.json
  test_vectors/mlspp/mlspp_transcript_1.json
  test_vectors/mlspp/mlspp_transcript_2.json
  test_vectors/mlspp/mlspp_transcript_3.json
  test_vectors/mlspp/mlspp_treemath.json
  tls-codec-derive/tests/decode.rs
  tls-codec-derive/tests/encode.rs
Labels: mls-spec change, size/xl, test-vectors

#411 Fixes to node encoding and the NodeType enum
  src/tree/codec.rs
  src/tree/node.rs
  test_vectors/kat_messages.json
  test_vectors/kat_tree_kem_openmls.json
Labels: size/xl

#410 Fix message processing in the managed testing framework
  tests/utils/managed_utils/client.rs
  tests/utils/managed_utils/errors.rs
Labels: size/s, tests

#414 Add ratchet tree extension to managed group
  src/group/managed_group/config.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/test_managed_group.rs
  src/key_store/mod.rs
  tests/test_decryption_key_index.rs
  tests/test_interop_scenarios.rs
  tests/test_managed_api.rs
  tests/test_managed_group.rs
  tests/test_tree_kem_kat.rs
Labels: size/m

#416 update evercrypt & hpke
  .github/workflows/tests.yml
  Cargo.toml
  src/ciphersuite/mod.rs
  src/group/mls_group/test_mls_group.rs
  src/group/tests/kat_messages.rs
  src/messages/mod.rs
  src/tree/sender_ratchet.rs
  src/utils.rs
  tests/utils/mls_utils/mod.rs
  tls-codec/Cargo.toml
Labels: size/s
