Repository openmls/openmls, pull requests merged in 2021-04, with the labels that each got.

#382 Make Secret protocol version and cipher suite aware
  Cargo.toml
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  src/ciphersuite/codec.rs
  src/ciphersuite/mod.rs
  src/ciphersuite/test_ciphersuite.rs
  src/ciphersuite/test_secrets.rs
  src/config/codec.rs
  src/config/errors.rs
  src/config/mod.rs
  src/extensions/capabilities_extension.rs
  src/extensions/test_extensions.rs
  src/framing/ciphertext.rs
  src/framing/errors.rs
  src/framing/plaintext.rs
  src/framing/test_framing.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/apply_commit.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_duplicate_extension.rs
  src/group/mls_group/test_mls_group.rs
  src/group/tests/kat_transcripts.rs
  src/key_packages/mod.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/messages/tests/test_pgs.rs
  src/messages/tests/test_proposals.rs
  src/messages/tests/test_welcome.rs
  src/schedule/kat_key_schedule.rs
  src/schedule/mod.rs
  src/schedule/psk.rs
  src/tree/mod.rs
  src/tree/private_tree.rs
  src/tree/secret_tree.rs
  src/tree/sender_ratchet.rs
  src/tree/tests/kat_encryption.rs
  src/tree/tests/test_hashes.rs
  src/tree/tests/test_resolution.rs
  src/tree/tests/test_secret_tree.rs
  tests/test_config.rs
  tests/test_encoding.rs
  tests/test_group.rs
  tests/utils/mls_utils/mod.rs
Labels: size/xl

#385 Change the Managed Group to accept a KeyStore ref instead of keeping a CredentialBundle ref
  src/group/managed_group/errors.rs
  src/group/managed_group/mod.rs
  src/group/managed_group/ser.rs
  src/group/managed_group/test_managed_group.rs
  src/key_store/errors.rs
  src/key_store/mod.rs
  src/key_store/test_key_store.rs
  src/lib.rs
  src/prelude.rs
  tests/test_decryption_key_index.rs
  tests/test_interop_scenarios.rs
  tests/test_managed_api.rs
  tests/test_managed_group.rs
  tests/utils/managed_utils/client.rs
  tests/utils/managed_utils/mod.rs
Labels: api, size/xl

#388 Fix error description visibility
  src/error.rs
Labels: size/s

#389 Revert "Fix error description visibility (#388)"
  src/error.rs
Labels: size/s

#391 Store encoded key_pacakge
  src/key_packages/codec.rs
  src/key_packages/errors.rs
  src/key_packages/mod.rs
Labels: size/s

#394 use tls-codec for tree hash structs
  src/ciphersuite/codec.rs
  src/codec/mod.rs
  src/key_packages/codec.rs
  src/tree/codec.rs
  src/tree/hashes.rs
  tls-codec-derive/src/lib.rs
  tls-codec/src/arrays.rs
  tls-codec/src/hpke.rs
  tls-codec/src/lib.rs
  tls-codec/src/primitives.rs
  tls-codec/src/tls_vec.rs
Labels: size/m

#390 API changes for TreeKEM Test Vector integration
  src/group/managed_group/mod.rs
  src/group/mls_group/create_commit.rs
  src/tree/hashes.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/tests/test_resolution.rs
  tests/test_interop_scenarios.rs
  tests/test_managed_group.rs
Labels: size/m
