Repository openmls/openmls, pull requests merged in 2021-12, with the labels that each got.

#590 fixing rustdoc warnings
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/error.rs
  openmls/src/extensions/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/membership.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/updates.rs
  openmls/src/group/managed_group/validation.rs
  openmls/src/group/mls_group/create_commit_params.rs
  openmls/src/group/mls_group/process.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/validation.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/kats/kat_treemath.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
Labels: size/m

#597 Replace 'unwrap' by 'expect' in tests
  openmls/benches/benchmark.rs
  openmls/src/credentials/tests.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/unit_tests.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_hashes.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_path_keys.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_treemath.rs
  openmls/src/tree/treemath.rs
  openmls/tests/test_config.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_framing.rs
  openmls/tests/test_group.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_key_packages.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_managed_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/xl

#570 Diff mechanics for the binary tree
  README.md
  openmls/src/binary_tree/array_representation.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/mod.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
Labels: size/xl

#596 crypto-subtle feature
  openmls/Cargo.toml
  openmls/src/ciphersuite/signature.rs
Labels: size/s

#602 New Rust version, new clippy warnings
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/application.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/mod.rs
Labels: size/s

#606 Add MLS10_256_DHKEMP384_AES256GCM_SHA384_P384 definition
  evercrypt_backend/src/provider.rs
  openmls/src/ciphersuite/ciphersuites.rs
  openmls/src/ciphersuite/mod.rs
  rust_crypto/src/lib.rs
  traits/src/types.rs
Labels: size/s

#595 Introduce the rstest framework
  interop_client/src/main.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/ciphersuite/tests/test_secrets.rs
  openmls/src/credentials/tests.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/mls_group/test_create_commit_params.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/unit_tests.rs
  openmls/src/test_utils/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_framing.rs
  openmls/tests/test_group.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_key_packages.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_managed_group.rs
  openmls/tests/utils/mls_utils/mod.rs
  openmls/tests/utils/mod.rs
  test_macros/Cargo.toml
  test_macros/src/lib.rs
  test_macros/tests/tests.rs
Labels: size/xl

#601 Introduce HashReference
  openmls/src/ciphersuite/hash_ref.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/sender.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
Labels: size/s

#604 Revert "New Rust version, new clippy warnings"
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/application.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/mod.rs
Labels: size/s

#607 Clippy warnings from Rust 1.57
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/application.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/mod.rs
Labels: size/s

#613 Fix interop client
  interop_client/Cargo.toml
  interop_client/src/main.rs
Labels: size/xs

#612 Fix the bug described in #600
  openmls/src/messages/tests/test_welcome.rs
Labels: size/s

#620 Fix clippy warnings after tree rewrite
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/treesync/treesync_node.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/test_managed_group.rs
Labels: size/m

#631 Sender and Commit Types
  openmls/src/framing/plaintext.rs
  openmls/src/framing/sender.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/create_commit_params.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/proposals.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/m

#629 Extend crypto traits and implementations with setup_and_export one-shots
  evercrypt_backend/src/provider.rs
  rust_crypto/src/lib.rs
  traits/src/crypto.rs
  traits/src/types.rs
Labels: size/m

#615 Replace PskFetcher callback with key store
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/create_commit_params.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/process.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/test_create_commit_params.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/key_store.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/l

#633 Assert that only members add a context to MlsPlaintextTBS
  openmls/src/framing/codec.rs
Labels: size/xs

#632 Add feature to decrypt application messages from past epochs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/message.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/managed_group/config.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/ser.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/past_secrets.rs
  openmls/src/group/mls_group/process.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_past_secrets.rs
  openmls/src/group/mls_group/validation.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/xl

#636 Rename MlsGroup to CoreGroup
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/ser.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/mls_group/apply_proposals.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/create_commit_params.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/process.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/test_proposals.rs
  openmls/src/group/mls_group/validation.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/lib.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_framing.rs
  openmls/tests/test_group.rs
  openmls/tests/test_managed_group.rs
  openmls/tests/utils/mls_utils/mod.rs
  openmls/tests/utils/mod.rs
Labels: size/l

#637 Move CoreGroup into a new directory
  openmls/src/framing/plaintext.rs
  openmls/src/framing/sender.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_create_commit_params.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_past_secrets.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/managed_group/membership.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/schedule/mod.rs
Labels: size/s

#638 Rename ManagedGroup to MlsGroup
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/main.rs
  interop_client/src/main.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/managed_group/application.rs
  openmls/src/group/managed_group/config.rs
  openmls/src/group/managed_group/creation.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/exporting.rs
  openmls/src/group/managed_group/membership.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/processing.rs
  openmls/src/group/managed_group/ser.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/managed_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/test_utils/test_framework/messages.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_managed_group.rs
Labels: size/l

#639 Move new MlsGroup to correct directories
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/resumption.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/mod.rs
  openmls/tests/test_mls_group.rs
Labels: size/xs

#640 Move code to prepare for CoreGroup feauture flag
  openmls/src/framing/mod.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
Labels: size/m

#647 Follow-up: Remove the last RefCell
  openmls/src/schedule/mod.rs
Labels: size/s

#649 Avoid clone in credential-getter of MlsGroup
  openmls/src/group/mls_group/mod.rs
Labels: size/xs

#559 Import existing key material for CredentialBundle
  openmls/Cargo.toml
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/credentials/tests.rs
Labels: size/s

#653 Fix bug in free leaf computation and add simple test
  openmls/src/treesync/diff.rs
  openmls/src/treesync/tests_and_kats.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
Labels: bug, size/s

#655 drop update from the key store trait
  memory_keystore/src/lib.rs
  traits/src/key_store.rs
Labels: size/s

#657 Remove UpdatePolicy stub
  openmls/src/group/mls_group/config.rs
  openmls/src/prelude.rs
Labels: size/s

#634 Partial support for external init
  openmls/src/ciphersuite/secret.rs
  openmls/src/extensions/errors.rs
  openmls/src/extensions/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_external_init.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/src/treesync/treesync_node.rs
  openmls/test_vectors/kat_messages.json
  traits/src/types.rs
Labels: size/xl

#648 Have `create_commit` return a `StagedCommit`
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/l

#660 Remove treesync branch from tests on CI
  .github/workflows/tests.yml
Labels: size/xs

#664 Add protocol version to PGS
  openmls/src/messages/public_group_state.rs
Labels: size/xs

#667 Refactor proposal queues
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/errors.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/test_mls_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/l

#666 Re-introduce parallelization
  openmls/Cargo.toml
  openmls/src/treesync/node/parent_node.rs
Labels: size/s

#668 Try a different clippy CI action
  .github/workflows/checks.yml
  .github/workflows/clippy.yml
Labels: size/s

#659 Introduce `pending_commit`
  delivery-service/ds/src/test.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude_test.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/diff.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_group.rs
  openmls/tests/test_mls_group.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/xl

#669 Fix most clippy warnings
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/schedule/mod.rs
Labels: size/xs

#675 Update codecov
  .github/workflows/coverage.yml
Labels: size/xs

#677 Add cargo doc checks
  .github/workflows/docs.yml
Labels: size/s

#674 Remove unnecessary `KeyPackageBundle` return during commit processing
  interop_client/src/main.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/treekem.rs
  openmls/tests/test_group.rs
Labels: size/m

#676 Enable processing of own external commits
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/test_utils/test_framework/client.rs
Labels: size/m

#679 Attempt to improve annotations
  .github/workflows/clippy.yml
  .github/workflows/docs.yml
Labels: size/s
