Repository openmls/openmls, pull requests merged in 2021-06, with the labels that each got.

#417 remove .travis.yml
  .travis.yml
Labels: size/s

#418 signature refactor
  src/ciphersuite/mod.rs
  src/ciphersuite/signable.rs
  src/extensions/test_extensions.rs
  src/framing/errors.rs
  src/framing/plaintext.rs
  src/framing/test_framing.rs
  src/group/errors.rs
  src/group/managed_group/errors.rs
  src/group/managed_group/mod.rs
  src/group/mls_group/create_commit.rs
  src/group/mls_group/mod.rs
  src/group/mls_group/new_from_welcome.rs
  src/group/mls_group/test_duplicate_extension.rs
  src/group/mls_group/test_mls_group.rs
  src/group/tests/kat_messages.rs
  src/key_packages/codec.rs
  src/key_packages/errors.rs
  src/key_packages/mod.rs
  src/key_packages/test_key_packages.rs
  src/lib.rs
  src/messages/codec.rs
  src/messages/mod.rs
  src/messages/tests/test_pgs.rs
  src/messages/tests/test_welcome.rs
  src/tree/errors.rs
  src/tree/mod.rs
  src/tree/node.rs
  src/tree/private_tree.rs
  src/tree/tests/kat_tree_kem.rs
  src/tree/tests/test_private_tree.rs
  tests/test_key_packages.rs
  tests/test_tree_kem_kat.rs
Labels: size/xl

#422 Enforce MlsPlaintext signature verification
  .gitignore
  cli/src/networking.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  openmls/fuzz/fuzz_targets/mls_plaintext_decode.rs
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/signable.rs
  openmls/src/codec/mod.rs
  openmls/src/config/codec.rs
  openmls/src/config/mod.rs
  openmls/src/credentials/codec.rs
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/life_time_extension.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/sender.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/codec.rs
  openmls/src/group/managed_group/callbacks.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/managed_group/test_managed_group.rs
  openmls/src/group/mls_group/apply_commit.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/new_from_welcome.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/key_packages/codec.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_proposals.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/codec.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/tree/codec.rs
  openmls/src/tree/mod.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/tests/kat_encryption.rs
  openmls/src/tree/tests/kat_tree_kem.rs
  openmls/test_vectors/kat_transcripts.json
  openmls/tests/test_encoding.rs
Labels: size/xl

#431 Make naming in MlsGroup API consistent
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/errors.rs
  openmls/src/group/managed_group/errors.rs
  openmls/src/group/managed_group/mod.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_duplicate_extension.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/src/tree/tests/kat_encryption.rs
  openmls/tests/test_encoding.rs
  openmls/tests/test_framing.rs
  openmls/tests/test_group.rs
  openmls/tests/test_managed_group.rs
  openmls/tests/utils/managed_utils/errors.rs
  openmls/tests/utils/mls_utils/mod.rs
Labels: size/m

#432 Move managed test utils into their own crate
  openmls/Cargo.toml
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_tree_kem_kat.rs
  openmls/tests/utils/mod.rs
  test_utils/Cargo.toml
  test_utils/src/client.rs
  test_utils/src/errors.rs
  test_utils/src/lib.rs
Labels: size/s

#433 Update .gitignore to reflect new directory structure
  .gitignore
Labels: size/xs
