Repository openmls/openmls, pull requests merged in 2022-01, with the labels that each got.

#684 Fix clippy warnings in tests
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/test_utils/test_framework/client.rs
Labels: size/s

#685 Make CoreGroup integration tests unit tests
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/utils.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_key_packages.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/utils/mod.rs
Labels: size/s

#687 Use MlsGroup in interop client
  interop_client/src/main.rs
Labels: size/m

#693 Reduce visibility
  .github/workflows/fuzz.yml
  openmls/fuzz/Cargo.toml
  openmls/fuzz/fuzz_targets/mls_message_decode.rs
  openmls/fuzz/fuzz_targets/mls_plaintext_decode.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_past_secrets.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_validation.rs
  openmls/src/messages/proposals.rs
  openmls/src/prelude_test.rs
Labels: size/l

#696 rename tree::index types
  openmls/src/schedule/message_secrets.rs
  openmls/src/tree/index.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/tree/treemath.rs
Labels: size/m

#700 Fix mdBook build/deploy
  .github/workflows/gh-pages.yml
Labels: size/xs

#702 Add manual trigger to ghpages workflow
  .github/workflows/gh-pages.yml
Labels: size/xs

#704 One more fix for gh-pages
  .github/workflows/gh-pages.yml
Labels: size/xs

#707 Remove trigger for mdBook
  .github/workflows/gh-pages.yml
Labels: size/s

#697 Allow self-removal during external commit ("resync")
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/errors.rs
  openmls/src/treesync/diff.rs
Labels: size/m

#706 Validate external commits
  book/src/message_validation.md
  openmls/src/framing/errors.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/treesync/treekem.rs
Labels: size/xl

#714 Builds the documentation in one go
  .github/workflows/gh-pages.yml
Labels: size/s

#716 Fix directory for gh-pages deployment
  .github/workflows/gh-pages.yml
Labels: size/xs

#728 Fix clippy errors
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/tree/treemath.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/treesync/treekem.rs
Labels: size/s

#742 Introduce missing public docs linting
  openmls/src/lib.rs
Labels: size/xs
