Repository openmls/openmls, pull requests merged in 2022-11, with the labels that each got.

#1083 Add a marker byte to tree hash input structs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/hashes.rs
  openmls/src/treesync/treesync_node.rs
Labels: size/m

#1086 docs: Add presentation language to `Extension{,Type}`.
  openmls/src/extensions/mod.rs
Labels: size/s

#1097 refactor: Rename `external_key_id` to `application_id`.
  openmls/src/extensions/application_id_extension.rs
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/codec.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/tests/test_key_packages.rs
Labels: size/m

#1105 Changes towards draft-16 wire format
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/l

#1109 Introduce MlsContentAuthData
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/tests/test_framing_validation.rs
Labels: size/m

#1110 Disable concurrency groups for clippy/coverage
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
Labels: size/xs

#1107 spec: Use a random group ID by default when creating groups.
  book/src/user_manual/create_group.md
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#1113 switch coverage CI workflow from nightly to stable
  .github/workflows/coverage.yml
Labels: size/xs, ci

#1111 Struct renaming and small framing bug fix
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/schedule/mod.rs
Labels: size/m

#1117 Remove signature key indirection
  CHANGELOG.md
  book/src/user_manual/processing.md
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/messages/proposals.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl

#1118 enable docs-building by CI on PRs
  .github/workflows/docs.yml
Labels: size/s

#1120 Require that unmerged_leaves be ordered
  openmls/src/treesync/node/codec.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/src/treesync/tests_and_kats/tests/test_unmerged_leaves.rs
Labels: size/m
