Repository openmls/openmls, pull requests merged in 2022-12, with the labels that each got.

#1127 Use GroupInfo instead of PublicGroupState. (2/2)
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/messages/tests/mod.rs
  openmls/src/messages/tests/test_export_group_info.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/prelude.rs
  openmls/src/schedule/mod.rs
  openmls/tests/test_external_commit.rs
Labels: size/xl

#1137 remove unnecessary lifetimes
  openmls/Cargo.toml
  openmls/src/group/core_group/mod.rs
Labels: size/s

#1147 Limit clippy to pushes
  .github/workflows/clippy.yml
Labels: size/xs

#1142 leaf secret cleanup
  openmls/src/ciphersuite/secret.rs
  openmls/src/key_packages/mod.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/s

#1153 spec: Remove `CapabilitiesExtension`.
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/codec.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1136 Fix validation order and major step towards fixing #979
  .github/workflows/interop_client.yml
  book/src/message_validation.md
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/message.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/external_proposals.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/xl

#1155 Cleanup around tree
  CHANGELOG.md
  cli/src/user.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/utils.rs
  openmls/src/lib.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1157 auto format book markdown
  book/src/SUMMARY.md
  book/src/introduction.md
  book/src/message_validation.md
  book/src/performance.md
  book/src/traits/traits.md
  book/src/traits/types.md
  book/src/user_manual/README.md
  book/src/user_manual/add_members.md
  book/src/user_manual/create_group.md
  book/src/user_manual/create_key_package.md
  book/src/user_manual/crypto-subtle.md
  book/src/user_manual/join_from_welcome.md
  book/src/user_manual/leaving.md
  book/src/user_manual/remove_members.md
Labels: size/m

#1159 More tree cleanup
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/sorted_iter.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
Labels: size/l

#1156 Remove LifetimeExtension
  openmls/src/extensions/codec.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/lifetime.rs
  openmls/tests/book_code.rs
Labels: size/m

#1161 Fix build status badge
  README.md
Labels: size/xs

#1165 Remove credential from KeyPackage
  delivery-service/ds-lib/src/lib.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/key_packages/codec.rs
  openmls/src/key_packages/mod.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/s

#1160 Drop key package bundle
  book/src/user_manual/create_group.md
  book/src/user_manual/create_key_package.md
  cli/src/identity.rs
  cli/src/user.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/benches/benchmark.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/config.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/key_store.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_export_group_info.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/prelude.rs
  openmls/src/prelude_test.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
  traits/src/key_store.rs
Labels: size/xl

#1158 Fix type boundaries, renaming and framing restructuring
  book/src/message_validation.md
  book/src/static/signable.svg
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/src/test.rs
  openmls/src/ciphersuite/hash_ref.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/message.rs
  openmls/src/framing/mls_auth_content.rs
  openmls/src/framing/mls_content.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_create_commit_params.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/external_proposals.rs
  openmls/src/messages/mod.rs
  openmls/src/prelude_test.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/messages.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/xl

#1164 Remove stale tests
  openmls/src/tree/tests_and_kats/unit_tests/test_hashes.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_index.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_path_keys.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_private_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_resolution.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_tree_truncation.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_util.rs
Labels: size/l

#1166 More treesync refactoring: split nodes
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/mod.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/tree_printing.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/treekem.rs
  openmls/src/treesync/treesync_node.rs
Labels: size/xl
