Repository openmls/openmls, pull requests merged in 2022-10, with the labels that each got.

#965 Add new_issue workflow
  .github/workflows/new_issue.yml
Labels: size/s

#977 chore: Add `.idea` (CLion) to .gitignore.
  .gitignore
Labels: size/xs

#1047 fix(docs): Fix description of validation.
  openmls/src/framing/validation.rs
Labels: size/xs

#1052 disable kat_messages and kat_encryption
  openmls/src/group/tests/kat_messages.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/s

#1060 docs: Describe creation of `backend` in the book.
  book/src/user_manual/README.md
  openmls/tests/book_code.rs
Labels: size/s

#1059 docs: Improve documentation.
  book/src/forward_secrecy.md
  book/src/introduction.md
  book/src/message_validation.md
  book/src/performance.md
  book/src/release_management.md
  book/src/traits/README.md
  book/src/traits/traits.md
  book/src/traits/types.md
  book/src/user_manual/add_members.md
  book/src/user_manual/application_messages.md
  book/src/user_manual/commit_to_proposals.md
  book/src/user_manual/create_group.md
  book/src/user_manual/create_key_package.md
  book/src/user_manual/crypto-subtle.md
  book/src/user_manual/group_config.md
  book/src/user_manual/identity.md
  book/src/user_manual/join_from_welcome.md
  book/src/user_manual/leaving.md
  book/src/user_manual/persistence.md
  book/src/user_manual/processing.md
  book/src/user_manual/remove_members.md
  book/src/user_manual/retrieve_member_list.md
  book/src/user_manual/updates.md
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/schedule/mod.rs
  traits/src/types.rs
Labels: size/m

#1066 ci: Eagerly cancel superseded workflows.
  .github/workflows/benches.yml
  .github/workflows/build.yml
  .github/workflows/checks.yml
  .github/workflows/cli.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/ds.yml
  .github/workflows/fuzz.yml
  .github/workflows/gh-pages.yml
  .github/workflows/interop_client.yml
  .github/workflows/tests.yml
Labels: size/s

#1068 docs: Make `openmls/README.md` a soft link to `README.md`.
  openmls/README.md
Labels: size/s

#1069 Follow up on #902 & #1055
  openmls/src/framing/message.rs
  openmls/src/framing/test_framing.rs
Labels: size/xs

#1071 docs: Use C-style comments in TLS presentation syntax.
  openmls/src/messages/mod.rs
Labels: size/xs

#1078 chore: Silence temporary warnings.
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/schedule/kat_key_schedule.rs
Labels: size/xs

#1076 Include ciphersuite in group context
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/test_vectors/kat_key_schedule_openmls.json
  openmls/test_vectors/kat_transcripts.json
Labels: size/xl
