Repository openmls/openmls, pull requests merged in 2022-02, with the labels that each got.

#703 Introduce thiserror
  openmls/Cargo.toml
  openmls/src/ciphersuite/signable.rs
  openmls/src/credentials/errors.rs
  openmls/src/credentials/mod.rs
  openmls/src/error.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/plaintext.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
  openmls/src/schedule/mod.rs
  openmls/src/treesync/diff.rs
Labels: size/m

#752 Review older PSK spec changes
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/prelude.rs
  openmls/src/schedule/kat_key_schedule.rs
Labels: size/s

#748 Update secret tree derivations
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/test_vectors/kat_encryption_openmls.json
Labels: mls-spec change, size/xl

#747 Expose list of member KeyPackages in public API
  book/src/user_manual/processing.md
  book/src/user_manual/remove_members.md
  book/src/user_manual/retrieve_member_list.md
  cli/src/user.rs
  openmls/src/group/mls_group/membership.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: api, size/m

#756 Remove sender from ApplicationMessage
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/s

#757 Have removed members merge proposal changes to their TreeSync instance
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
Labels: size/m

#762 set metadata for all crate
  evercrypt_backend/Cargo.toml
  memory_keystore/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#766 tls_codec v.0.2.0, hpke-rs v.0.1.0
  cli/Cargo.toml
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds/Cargo.toml
  evercrypt_backend/Cargo.toml
  interop_client/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#782 Cleaned up rustdocs for extensions
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/external_key_id_extension.rs
  openmls/src/extensions/life_time_extension.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/parent_hash_extension.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/group/group_context.rs
Labels: size/m

#786 Add documentation for leaving and getting removed
  book/src/user_manual/leaving.md
  book/src/user_manual/remove_members.md
  openmls/tests/book_code.rs
Labels: documentation, size/s

#793 More validation
  book/src/message_validation.md
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/tests/test_external_commit_validation.rs
Labels: size/m

#798 Fix version in README
  README.md
Labels: size/xs

#792 Add `member` endpoint
  book/src/user_manual/retrieve_member_list.md
  openmls/src/group/mls_group/membership.rs
  openmls/tests/book_code.rs
Labels: api, size/s

#806 Commit message validation and tests
  book/src/message_validation.md
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/mod.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/ciphersuite/mac.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/messages/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/treekem.rs
Labels: size/xl, tests

#813 Error cleanup 4
  cli/src/user.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/framing/ciphertext.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/treekem.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#825 Remove public members from GroupEpoch and EncryptedGroupSecrets
  delivery-service/ds/src/main.rs
  interop_client/src/main.rs
  openmls/src/framing/plaintext.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_past_secrets.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/treekem.rs
Labels: size/m

#822 Proposal validation tests (receiver side) for ValSem100-103
  book/src/message_validation.md
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/mod.rs
Labels: size/m

#830 Add tests for ValSem107 to ValSem112
  book/src/message_validation.md
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: tests, size/l

#832 Add validation step and a corresponding test for ValSem106
  book/src/message_validation.md
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/mod.rs
Labels: size/m, tests

#834 make key_store module private
  openmls/src/lib.rs
Labels: size/xs

#835 README update and Cargo.toml updates
  LICENSE
  README.md
  cli/Cargo.toml
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds/Cargo.toml
  interop_client/Cargo.toml
Labels: size/s

#836 Fix message rustdocs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/public_group_state.rs
Labels: size/m

#838 clean up MlsGroup config and harder rustdoc requirements
  interop_client/src/main.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/error.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#839 Fix schedule rustdocs
  interop_client/src/main.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/lib.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/mod.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#844 Capitalize readme.md filename
  traits/README.md
Labels: size/xs

#845 Force clean stage for tarpaulin
  .github/workflows/coverage.yml
Labels: size/xs

#840 Remove tree rewrite chapter from book
  book/src/SUMMARY.md
  book/src/tree_rewrite.md
Labels: size/m

#848 common readme
  Developer.md
  README.md
  book/README.md
  book/src/SUMMARY.md
  openmls/src/error.rs
  openmls/src/lib.rs
Labels: size/m

#850 Move verification chapter to signable module docs
  book/src/SUMMARY.md
  book/src/type_enfored_verification.md
  openmls/src/ciphersuite/signable.rs
Labels: documentation, size/s

#851 Ensure that only things that are actually needed are public
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/mod.rs
  openmls/src/ciphersuite/aead.rs
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/mac.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/reuse_guard.rs
  openmls/src/ciphersuite/secret.rs
  openmls/src/credentials/mod.rs
  openmls/src/error.rs
  openmls/src/extensions/capabilities_extension.rs
  openmls/src/extensions/mod.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/errors.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/prelude.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/tree/index.rs
  openmls/src/tree/mod.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/treesync/mod.rs
  openmls/src/versions.rs
Labels: size/m

#853 Remove re-exports from lib.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/lib.rs
  openmls/src/treesync/mod.rs
Labels: size/s

#856 bump evercrypt to fix Windows builds
  evercrypt_backend/Cargo.toml
Labels: size/xs

#854 Import readme for book intro
  README.md
  book/src/SUMMARY.md
  book/src/introduction.md
Labels: size/s

#855 Expanding on the credential and key package sections of the book
  book/src/SUMMARY.md
  book/src/user_manual/create_key_package.md
  book/src/user_manual/identity.md
Labels: size/s

#859 Rephrase platform support
  README.md
Labels: size/xs

#861 Fix link in `public_group_state` docs
  openmls/src/messages/public_group_state.rs
Labels: size/xs

#862 Trim key schedule docs
  openmls/src/schedule/mod.rs
Labels: size/m

#864 The linked file must be in the crate folder
  openmls/README.md
  openmls/src/lib.rs
Labels: size/s

#865 v0.4 release
  evercrypt_backend/Cargo.toml
  memory_keystore/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#867 Extend README with intro
  book/src/introduction.md
  openmls/README.md
Labels: size/xs

#868 Fix correct README
  README.md
Labels: size/xs
