Repository openmls/openmls, pull requests merged in 2023-11, with the labels that each got.

#1448 Add ability to set RequiredCapabilities in MlsGroupConfig builder
  openmls/src/group/mls_group/config.rs
Labels: size/s

#1450 Don't build the fuzzer as part of the workspace on CI
  .github/workflows/build_test_workspace.yml
Labels: size/xs

#1449 Last resort extension
  openmls/src/extensions/codec.rs
  openmls/src/extensions/last_resort.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/key_packages/mod.rs
Labels: size/m
