Repository openmls/openmls, pull requests merged in 2023-05, with the labels that each got.

#1380 More LeafNode validation
  book/src/message_validation.md
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/errors.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/src/treesync/treekem.rs
Labels: size/l

#1382 Add credential validation section to book
  book/src/SUMMARY.md
  book/src/user_manual/credential_validation.md
Labels: size/s

#1367 fix: EncryptionKeyPair has the wrong MlsEntityId
  openmls/src/treesync/node/encryption_keys.rs
Labels: waiting-on-author

#1369 feat: wrap sensitive types in order to zero the memory on drop (#1240)
  evercrypt_backend/Cargo.toml
  evercrypt_backend/src/provider.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/aead.rs
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/mac.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/secret.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls_rust_crypto/src/provider.rs
  traits/Cargo.toml
  traits/src/crypto.rs
  traits/src/types.rs
Labels: waiting-on-review

#1387 Cleanup after removing CredentialBundle
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcript_hashes.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/lib.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_treemath.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1388 Improve documentation of commit_to_pending_proposals
  openmls/src/group/mls_group/processing.rs
Labels: size/xs

#1393 Prepare 0.5 release
  CHANGELOG.md
  basic_credential/Cargo.toml
  evercrypt_backend/Cargo.toml
  interop_client/Cargo.toml
  memory_keystore/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
  traits/src/types.rs
Labels: size/s

#1396 Upgrade P256
  openmls_rust_crypto/Cargo.toml
  openmls_rust_crypto/src/provider.rs
Labels: size/s

#1390 Minor API changes
  openmls/src/framing/public_message_in.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/messages/group_info.rs
Labels: api, size/m
