Repository openmls/openmls, pull requests merged in 2023-07, with the labels that each got.

#1413 Update hardcoded KeyPackage
  openmls/src/key_packages/mod.rs
Labels: size/s

#1417 Ensure Add proposal order is maintained; add test
  openmls/src/group/core_group/proposals.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#1398 Release v0.5
  README.md
  basic_credential/Cargo.toml
  delivery-service/ds/src/test.rs
  interop_client/Cargo.toml
  memory_keystore/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1418 Rename basic credential readme
  basic_credential/README.md
Labels: size/xs

#1419 fix keywords for crate.io
  openmls/Cargo.toml
Labels: size/xs

#1420 Update tree operations tv from mlswg/mls-implementations#168
  openmls/src/group/public_group/mod.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/test_vectors/tree-operations.json
Labels: size/s

#1426 Clarify unsupported targets in README
  README.md
Labels: size/xs

#1428 update tree operations tv from mlswg/mls-implementations#170
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/test_vectors/tree-operations.json
Labels: size/s
