Repository openmls/openmls, pull requests merged in 2023-09, with the labels that each got.

#1434 Make the secret tree panic free
  openmls/src/tree/secret_tree.rs
Labels: size/m

#1440 Remove Send + Sync requirement for key store
  traits/src/key_store.rs
Labels: size/xs

#1441 Remove duplicate structs
  openmls/src/framing/private_message_in.rs
  openmls/src/framing/public_message_in.rs
Labels: size/s
