Repository openmls/openmls, pull requests merged in 2023-03, with the labels that each got.

#1304 spec: Use `ExpandWithLabel` to derive welcome nonce/key.
  openmls/src/schedule/mod.rs
  openmls/test_vectors/welcome.json
Labels: size/s

#1307 spec: Change MLS-Exporter label from "exporter" to "exported".
  openmls/src/schedule/mod.rs
  openmls/test_vectors/key-schedule.json
Labels: size/m

#1308 Require path for GroupContextExtensions
  openmls/src/messages/proposals.rs
Labels: size/s

#1310 Bump tls codec version to pre-release
  basic_credential/Cargo.toml
  cli/Cargo.toml
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds/Cargo.toml
  interop_client/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1313 move tls_codec dependency to workspace
  Cargo.toml
  basic_credential/Cargo.toml
  cli/Cargo.toml
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds/Cargo.toml
  interop_client/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1312 interop: Update key schedule.
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/test_vectors/key-schedule.json
Labels: size/xl

#1320 chore: Fix new Clippy lints.
  openmls/src/extensions/mod.rs
  openmls/src/treesync/diff.rs
Labels: size/xs

#1315 spec: Make the ratchet tree non-malleable.
  book/src/message_validation.md
  openmls/src/extensions/mod.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/test_vectors/messages.json
Labels: size/xl

#1321 Acknowledge Zulip
  README.md
Labels: size/xs

#1309 rename PrivateContentTbe to PrivateMessageContent
  book/src/message_validation.md
  openmls/src/framing/codec.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/private_message_in.rs
  openmls/src/group/tests/test_framing.rs
Labels: size/s

#1324 Cleanup after #1318
  openmls/src/framing/codec.rs
  openmls/src/framing/mls_auth_content.rs
  openmls/src/framing/mls_auth_content_in.rs
  openmls/src/framing/mls_content.rs
  openmls/src/framing/mls_content_in.rs
  openmls/src/framing/private_message_in.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/public_message_in.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/schedule/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/treekem.rs
Labels: size/l

#1317 interop runner
  .github/workflows/coverage.yml
  Cargo.toml
  interop_client/Cargo.toml
  interop_client/build.rs
  interop_client/proto/mls_client.proto
  interop_client/src/main.rs
  openmls/src/framing/message_in.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/prelude.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
Labels: size/xl

#1328 refactor: Store PSKs independently from nonce.
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/errors.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_psk_secret.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
Labels: size/m

#1329 handle interop PSKs
  interop_client/src/main.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/psk.rs
  openmls/src/messages/proposals.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
Labels: size/m

#1331 interop: Extend passive client interop tests.
  book/src/message_validation.md
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/errors.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/psk.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/test_vectors/passive-client-handling-commit.json
  openmls/test_vectors/passive-client-random.json
Labels: size/xl
