Repository openmls/openmls, pull requests merged in 2023-02, with the labels that each got.

#1237 chore: autofix new clippy lints from 1.67
  cli/src/backend.rs
  cli/src/main.rs
  cli/src/networking.rs
  cli/src/user.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/ciphersuite/hash_ref.rs
  openmls/src/credentials/codec.rs
  openmls/src/error.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/mls_content.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/tree_printing.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_mls_group.rs
  traits/src/types.rs
Labels: size/m

#1236 test vectors 1/n
  openmls/src/ciphersuite/aead.rs
  openmls/src/framing/mls_content.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/public_message.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/group_context.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/tree/tests_and_kats/kats.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/test_vectors/kat_encryption_openmls.json
Labels: size/xl

#1239 tls codec cleanup
  openmls/src/extensions/application_id_extension.rs
  openmls/src/extensions/codec.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/sender.rs
  openmls/src/messages/proposals.rs
Labels: size/m

#1218 Introduce PublicGroup
  interop_client/src/main.rs
  openmls/benches/benchmark.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/public_group/diff/process_path.rs
  openmls/src/group/public_group/errors.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/prelude.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/treekem.rs
  openmls/tests/book_code.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl

#1235 feat: review keystore
  basic_credential/Cargo.toml
  basic_credential/src/lib.rs
  memory_keystore/Cargo.toml
  memory_keystore/src/lib.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_store.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/prelude.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/psk.rs
  openmls/src/treesync/node/encryption_keys.rs
  traits/src/key_store.rs
  traits/src/types.rs
Labels: size/m

#1241 refactor: Derive `tls_codec` implementations for `Proposal`.
  openmls/src/messages/codec.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
Labels: size/m

#1247 enable workflows for all PRs
  .github/workflows/benches.yml
  .github/workflows/build.yml
  .github/workflows/checks.yml
  .github/workflows/cli.yml
  .github/workflows/clippy.yml
  .github/workflows/docs.yml
  .github/workflows/ds.yml
  .github/workflows/fuzz.yml
  .github/workflows/tests.yml
Labels: size/s

#1245 Updating treemath and encryption test vectors
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/test_vectors/kat_encryption_openmls.json
  openmls/test_vectors/kat_treemath_openmls.json
Labels: size/xl

#1249 fix application secret generation
  openmls/src/tree/secret_tree.rs
  openmls/test_vectors/kat_encryption_openmls.json
Labels: size/xl

#1251 Clean up unused dependencies
  openmls/Cargo.toml
Labels: size/s

#1256 Move validation into public group
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/test_utils/test_framework/client.rs
Labels: size/s

#1260 hpke encrypt with label
  openmls/src/ciphersuite/hpke.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/signature.rs
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/public_group/diff/process_path.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/treekem.rs
Labels: size/m

#1262 crypto basic kat
  basic_credential/Cargo.toml
  basic_credential/src/lib.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/tests.rs
  openmls/src/ciphersuite/tests/kat_crypto_basics.rs
  openmls/test_vectors/crypto-basics.json
Labels: size/l

#1267 update protocol version to u16
  openmls/src/credentials/tests.rs
  openmls/src/versions.rs
Labels: size/s

#1269 update treemath kat
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/test_vectors/tree-math.json
Labels: size/xl

#1263 Move `create_commit` into public_group
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/create_commit.rs
  openmls/src/group/public_group/create_commit_params.rs
  openmls/src/group/public_group/diff/process_path.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/tests/kat_messages.rs
Labels: size/m

#1276 Update key schedule test vectors
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/public_group/create_commit.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/test_vectors/key-schedule.json
Labels: size/l

#1266 Move `stage_commit` into `PublicGroup`
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/treesync/diff.rs
Labels: size/l

#1278 Secret tree test vector
  openmls/src/ciphersuite/secret.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/tree/tests_and_kats/kats.rs
  openmls/src/tree/tests_and_kats/kats/secret_tree.rs
  openmls/test_vectors/kat_key_schedule_openmls.json
  openmls/test_vectors/secret-tree.json
Labels: size/xl

#1281 PSK secret KAT
  openmls/src/schedule/kat_psk_secret.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/test_vectors/psk_secret.json
Labels: size/xl

#1282 Fix the key schedule KAT
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/psk.rs
  openmls/test_vectors/key-schedule.json
Labels: size/m

#1284 Make PSK secret sometimes null in key schedule KAT
  openmls/src/framing/test_framing.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/test_vectors/key-schedule.json
Labels: size/m

#1290 Tree validation KAT
  openmls/src/treesync/diff.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/kats.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/test_vectors/tree-validation.json
Labels: size/xl

#1280 Introduce an API that allows message processing by a `PublicGroup`
  openmls/src/framing/public_message.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/public_group/create_commit.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/errors.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/tests/book_code.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_mls_group.rs
Labels: api, size/xl

#1296 Improve `PublicGroup` abstraction
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/tree_printing.rs
  openmls/src/group/tests/utils.rs
  openmls/src/treesync/mod.rs
Labels: size/m

#1294 Small refactor of CoreGroup message processing
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
Labels: size/l

#1291 message protection kat
  openmls/src/framing/private_message.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/psk.rs
  openmls/src/tree/tests_and_kats/kats.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/test_vectors/message-protection.json
Labels: size/l

#1271 CI improvements
  .github/dependabot.yml
  .github/workflows/benches.yml
  .github/workflows/build.yml
  .github/workflows/checks.yml
  .github/workflows/cli.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/ds.yml
  .github/workflows/fuzz.yml
  .github/workflows/gh-pages.yml
  .github/workflows/tests.yml
Labels: size/m

#1270 refactor: Introduce `RatchetTreeExported` to unify `Vec<Option<Node>>`-handling.
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/tree_printing.rs
  openmls/src/group/tests/utils.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
Labels: size/l
