Repository openmls/openmls, pull requests merged in 2023-01, with the labels that each got.

#1168 Filtered direct path
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/treekem.rs
Labels: size/m

#1171 ci: Run Clippy during pull_request event.
  .github/workflows/clippy.yml
  delivery-service/ds-lib/src/lib.rs
  openmls/src/messages/proposals.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/treesync_node.rs
Labels: size/s

#1170 feat: Introduce `Extensions` type.
  openmls/src/extensions/codec.rs
  openmls/src/extensions/errors.rs
  openmls/src/extensions/mod.rs
Labels: size/m

#1173 feat: Introduce `KeyPackageBuilder`.
  cli/src/identity.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/benches/benchmark.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1179 Full tree
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/binary_tree/test_binary_tree.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/treesync_node.rs
  openmls/test_vectors/kat_treemath_openmls.json
Labels: size/xl

#1177 Ensure init_key and encryption_key are different
  book/src/message_validation.md
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/config.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_export_group_info.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/src/treesync/treekem.rs
  openmls/tests/book_code.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_mls_group.rs
  traits/src/types.rs
Labels: size/xl

#1172 Extend WireFormat as per spec
  cli/src/backend.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/Cargo.toml
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/message.rs
  openmls/src/framing/message_in.rs
  openmls/src/framing/message_out.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/public_message.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/tests/book_code.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl

#1178 spec: Use `Extensions` instead of `Vec<Extension>`.
  delivery-service/ds/src/test.rs
  openmls/src/extensions/errors.rs
  openmls/src/extensions/mod.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_duplicate_extension.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/codec.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/tests/test_codec.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1182 fix: Remove `GroupInfo`s `tls_codec::Deserialize` implementation.
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
Labels: size/s

#1184 fix: Remove `Verifiable` implementation of `GroupInfo`.
  openmls/src/messages/mod.rs
Labels: size/s

#1188 Introduce new parent hash
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/hashes.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/treesync_node.rs
Labels: size/m

#1191 signable with keys
  openmls/src/ciphersuite/signable.rs
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/mod.rs
  openmls/src/framing/mls_auth_content.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/errors.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/messages/tests/test_export_group_info.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1193 update with leaf node
  CHANGELOG.md
  interop_client/src/main.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1192 Allow to pass `Capabilities` and `Extensions` when creating an `OpenMlsLeafNode`.
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/mod.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1199 chore: Remove `LifetimeExtension`.
  openmls/src/extensions/errors.rs
  openmls/src/extensions/life_time_extension.rs
  openmls/src/treesync/node/leaf_node/lifetime.rs
Labels: size/m

#1196 chore: Cleanup `LeafNode` a bit.
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1203 Towards a public ratchet tree (without private values)
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  memory_keystore/src/lib.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/core_group/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/external_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/node/codec.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/src/treesync/treekem.rs
  openmls/src/treesync/treesync_node.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
  openmls_rust_crypto/src/lib.rs
  traits/src/key_store.rs
  traits/src/types.rs
Labels: size/xl

#1206 refactor/correctness: Move `GroupInfo` into own module and tighten-up serialization.
  openmls/src/framing/message_in.rs
  openmls/src/framing/message_out.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/group_info.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_export_group_info.rs
  openmls/src/messages/tests/test_pgs.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/tests/test_external_commit.rs
Labels: size/l

#1216 Pull own_index out of TreeSync
  memory_keystore/src/lib.rs
  openmls/src/group/core_group/apply_proposals.rs
  openmls/src/group/core_group/create_commit.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/src/treesync/treekem.rs
  traits/src/key_store.rs
Labels: size/l

#1224 ci: Fix coverage job.
  .github/workflows/coverage.yml
Labels: size/s

#1229 docs/spec: Update `Proposal`s to draft-ietf-mls-protocol-17.
  openmls/src/group/core_group/proposals.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/proposals.rs
Labels: size/m

#1227 re-enable valsem110 test
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1190 Fix AuthenticatedContent serialization
  openmls/src/framing/message_out.rs
  openmls/src/framing/mls_auth_content.rs
  openmls/src/framing/mls_content.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/kat_transcripts.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
Labels: size/l

#1228 Remove invalid_plaintext_signature test
  openmls/src/framing/test_framing.rs
Labels: size/m
