Repository openmls/openmls, pull requests merged in 2023-04, with the labels that each got.

#1333 Ensure to fully consume TLS input (in tests).
  fuzz/fuzz_targets/mls_message_decode.rs
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/framing/mod.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/kat_welcome.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcript_hashes.rs
  openmls/src/messages/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_kem.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/tests/book_code.rs
Labels: size/m

#1339 Remove draft version
  README.md
Labels: size/xs

#1344 update to tls_codec 0.3.0-pre.2
  Cargo.toml
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/framing/mod.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/kat_welcome.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcript_hashes.rs
  openmls/src/messages/mod.rs
  openmls/src/prelude.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
Labels: size/s

#1343 feat/fix: Handle unknown extensions and do not reorder them.
  openmls/src/extensions/codec.rs
  openmls/src/extensions/mod.rs
Labels: size/m

#1358 ci: Build workspace.
  .github/workflows/build_test_workspace.yml
  .github/workflows/cli.yml
  .github/workflows/ds.yml
Labels: size/m

#1351 Work towards interop.
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/kat_welcome.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/psk.rs
  openmls/src/group/mls_group/resumption.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/messages/group_info.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/errors.rs
  openmls/src/schedule/kat_psk_secret.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/utils.rs
Labels: size/xl

#1359 Make interop work.
  openmls/src/group/core_group/mod.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/public_group/mod.rs
Labels: size/s

#1365 Tree operations KAT
  openmls/src/group/public_group/mod.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/tests_and_kats/kats.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/test_vectors/tree-operations.json
Labels: size/m

#1363 docs: Describe interop workflow.
  interop_client/README.md
  interop_client/docker/mlspp/Dockerfile
  interop_client/docker/test-runner/Dockerfile
  interop_client/docker/test-runner/main.go.patch
Labels: size/m

#1370 interop/ci: Test interop between OpenMLS and MLS++.
  .github/workflows/interop.yml
Labels: size/m

#1373 Update interop.yml job name
  .github/workflows/interop.yml
Labels: size/xs

#1376 Bump tls codec version to 0.3.0-pre.3
  Cargo.toml
Labels: size/xs

#1377 Remaining KeyPackage validation
  openmls/src/framing/codec.rs
  openmls/src/framing/message_in.rs
  openmls/src/framing/message_out.rs
  openmls/src/framing/mls_auth_content_in.rs
  openmls/src/framing/mls_content_in.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/key_package_in.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
Labels: size/m
