Repository openmls/openmls, pull requests merged in 2024-07, with the labels that each got.

#1602 Make backtrace an optional feature
  openmls/Cargo.toml
Labels: size/s

#1600 Some more benchmarks
  .github/workflows/benches.yml
  memory_storage/src/lib.rs
  memory_storage/src/persistence.rs
  openmls/Cargo.toml
  openmls/examples/large-groups.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/treesync_node.rs
  openmls_rust_crypto/Cargo.toml
  openmls_rust_crypto/src/lib.rs
  openmls_rust_crypto/src/provider.rs
Labels: size/l

#1608 Move some external commit tests to MlsGroup
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_external_commit.rs
Labels: size/m

#1603 Assorted Documentation Fixes for v0.6
  book/src/SUMMARY.md
  book/src/app_validation.md
  book/src/performance.md
  book/src/traits/traits.md
  book/src/user_manual/README.md
  book/src/user_manual/persistence.md
  traits/src/storage.rs
Labels: size/m

#1601 De-duplicate ProposalStore
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_create_commit_params.rs
  openmls/src/group/core_group/test_external_init.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/utils.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
Labels: size/l

#1611 Remove clippy warnings & change CI
  .github/workflows/clippy.yml
  cli/src/user.rs
  interop_client/src/main.rs
  memory_storage/tests/proposals.rs
  openmls/benches/benchmark.rs
  openmls/examples/large-groups.rs
Labels: size/s

#1606 LeafNode parameters
  CHANGELOG.md
  book/src/user_manual/updates.md
  interop_client/src/main.rs
  openmls/benches/benchmark.rs
  openmls/examples/large-groups.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/credentials/mod.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/key_packages/mod.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/frankenstein/leaf_node.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/src/treesync/treesync_node.rs
  openmls/tests/book_code.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl

#1612 more update proposal tests
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mls_group/updates.rs
Labels: size/m

#1599 Test all Validation Checks for GroupContextExtensions
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/group_context_extensions.rs
  openmls/src/group/tests/mod.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/frankenstein/framing.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl, tests, validation

#1610 Add a KAT for testing storage stability
  memory_storage/src/lib.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/past_secrets.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/schedule/message_secrets.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/storage.rs
  openmls/src/storage/kat_storage_stability.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/test_vectors/storage-stability.json
Labels: tests, size/l

#1615 Change how the AAD is set
  CHANGELOG.md
  book/src/SUMMARY.md
  book/src/user_manual/aad.md
  cli/src/user.rs
  interop_client/src/main.rs
  memory_storage/src/lib.rs
  memory_storage/src/test_store.rs
  openmls/src/framing/validation.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/tests/mod.rs
  openmls/src/group/tests/test_aad.rs
  openmls/tests/book_code.rs
  traits/src/storage.rs
Labels: size/m

#1619 Migrate tests to `MlsGroup`
  openmls/src/extensions/tests.rs
  openmls/src/framing/mls_auth_content.rs
  openmls/src/framing/tests.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/tests_and_kats/tests/core_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/external_init.rs
  openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
  openmls/src/group/mls_group/tests_and_kats/utils.rs
  openmls/src/group/tests_and_kats/kats/messages.rs
  openmls/src/group/tests_and_kats/tests/group.rs
  openmls/src/messages/tests/export_group_info.rs
  openmls/src/test_utils/frankenstein/commit.rs
  openmls/src/treesync/diff.rs
Labels: size/xl

#1625 Bump versions and remove git deps for release
  CHANGELOG.md
  basic_credential/Cargo.toml
  interop_client/Cargo.toml
  libcrux_crypto/Cargo.toml
  libcrux_crypto/src/lib.rs
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  openmls_test/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1626 Make the versions of all the intermediate packages pre-release as well
  basic_credential/Cargo.toml
  libcrux_crypto/Cargo.toml
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  openmls_test/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1627 Downgrade tls_codec to 0.4.1
  Cargo.toml
  basic_credential/Cargo.toml
  libcrux_crypto/Cargo.toml
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1628 Add metadata to openmls_test crate
  openmls_test/Cargo.toml
Labels: size/xs

#1630 Set versions for openmls_test
  openmls_test/Cargo.toml
Labels: size/xs

#1634 Small clippy fixes
  interop_client/src/main.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/lib.rs
  openmls/src/messages/external_proposals.rs
  openmls/src/tree/sender_ratchet.rs
Labels: size/s

#1633 Remove `aad` getter from storage provider trait
  memory_storage/src/lib.rs
  memory_storage/src/test_store.rs
  traits/src/storage.rs
Labels: size/s

#1632 openmls v0.6.0-pre.2
  openmls/Cargo.toml
Labels: size/xs

#1631 Migrate remaining `CoreGroup` tests to `MlsGroup`
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/tests_and_kats/tests/encoding.rs
  openmls/src/group/tests_and_kats/tests/framing.rs
  openmls/src/group/tests_and_kats/utils.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
Labels: size/l
