Repository openmls/openmls, pull requests merged in 2024-09, with the labels that each got.

#1651 Update links
  Developer.md
  README.md
  book/src/introduction.md
  openmls/src/group/mls_group/config.rs
  openmls/src/group/tests_and_kats/tests/commit_validation.rs
  openmls/src/group/tests_and_kats/tests/framing_validation.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
  openmls/src/lib.rs
Labels: size/s

#1652 Bump crate versions for v0.6
  CHANGELOG.md
  basic_credential/Cargo.toml
  libcrux_crypto/Cargo.toml
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  openmls_test/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1653 Fix docs
  openmls/src/ciphersuite/signable.rs
Labels: size/xs

#1655 Add check and (basic) test for check 701: remove can't contain inde to blank leaf
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests_and_kats/tests/remove_operation.rs
Labels: size/m
