Repository openmls/openmls, pull requests merged in 2024-08, with the labels that each got.

#1637 Remove MlsSerializedMlsGroup
  cli/src/user.rs
  openmls/examples/large-groups.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/prelude.rs
Labels: size/m

#1638 Remove serde for PublicGroup and CoreGroup
  CHANGELOG.md
  openmls/src/group/core_group/mod.rs
  openmls/src/group/public_group/mod.rs
Labels: size/s

#1640 Align storage provider naming
  memory_storage/src/lib.rs
  memory_storage/src/test_store.rs
  traits/src/public_storage.rs
  traits/src/storage.rs
Labels: size/xs

#1641 Consistent handling of queued proposals.
  CHANGELOG.md
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/tests.rs
  openmls/tests/book_code.rs
  traits/src/public_storage.rs
Labels: size/m

#1642 Remove OpenMlsProvider dependency of PublicGroup.
  CHANGELOG.md
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests_and_kats/tests/external_add_proposal.rs
  openmls/src/group/tests_and_kats/tests/external_commit_validation.rs
  openmls/src/group/tests_and_kats/tests/external_remove_proposal.rs
  openmls/src/group/tests_and_kats/tests/framing_validation.rs
  openmls/src/group/tests_and_kats/tests/group_context_extensions.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/tests/book_code.rs
  openmls/tests/mls_group.rs
Labels: size/m

#1644 Fix `MlsGroup::delete()` function to delete encryption keypairs
  basic_credential/src/lib.rs
  memory_storage/src/lib.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
Labels: size/s

#1646 Fix Missing Persisting of Message Secrets
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/tests_and_kats/tests/past_secrets.rs
Labels: size/s

#1648 Bump versions and fix build error
  basic_credential/Cargo.toml
  delivery-service/ds/Cargo.toml
  libcrux_crypto/Cargo.toml
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  openmls_test/Cargo.toml
  traits/Cargo.toml
Labels: size/s

#1649 Slightly refactor public group storage interface
  openmls/src/group/core_group/mod.rs
  openmls/src/group/public_group/mod.rs
  traits/src/public_storage.rs
Labels: size/s

#1647 Remove `CoreGroup`
  cli/src/openmls_rust_persistent_crypto.rs
  memory_storage/src/lib.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/create_commit_params.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/application.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/past_secrets.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/proposal_store.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/tests_and_kats/tests/core_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/create_commit_params.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mod.rs
  openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests_and_kats/mod.rs
  openmls/src/group/tests_and_kats/tests/commit_validation.rs
  openmls/src/group/tests_and_kats/tests/encoding.rs
  openmls/src/group/tests_and_kats/tests/external_commit_validation.rs
  openmls/src/group/tests_and_kats/tests/external_remove_proposal.rs
  openmls/src/group/tests_and_kats/tests/framing.rs
  openmls/src/group/tests_and_kats/tests/framing_validation.rs
  openmls/src/group/tests_and_kats/tests/group_context_extensions.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
  openmls/src/group/tests_and_kats/tree_printing.rs
  openmls/src/group/tests_and_kats/utils.rs
  openmls/src/prelude.rs
  openmls/src/schedule/mod.rs
  openmls/src/storage.rs
  openmls/src/storage/kat_storage_stability.rs
  openmls/src/test_utils/test_framework/errors.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/tests/external_commit.rs
  traits/src/storage.rs
Labels: size/xl
