Repository openmls/openmls, pull requests merged in 2024-01, with the labels that each got.

#1466 minor changes to silence clippy warnings
  openmls/src/credentials/codec.rs
  openmls/src/group/mod.rs
  openmls/src/prelude.rs
Labels: size/s

#1467 perf: small perf improvements
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
Labels: size/xs

#1461 Add `update_path_leaf_node` method to `StagedCommit`.
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/test_mls_group.rs
Labels: size/m

#1468 Derive DeserializeBytes alongside Deserialize
  basic_credential/src/lib.rs
  delivery-service/ds-lib/src/lib.rs
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/hash_ref.rs
  openmls/src/ciphersuite/hpke.rs
  openmls/src/ciphersuite/mac.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/reuse_guard.rs
  openmls/src/ciphersuite/signature.rs
  openmls/src/credentials/codec.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/application_id_extension.rs
  openmls/src/extensions/codec.rs
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/extensions/last_resort.rs
  openmls/src/extensions/mod.rs
  openmls/src/extensions/ratchet_tree_extension.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/framing/message_in.rs
  openmls/src/framing/mls_content_in.rs
  openmls/src/framing/mod.rs
  openmls/src/framing/private_message_in.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/public_message_in.rs
  openmls/src/framing/sender.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mod.rs
  openmls/src/key_packages/key_package_in.rs
  openmls/src/key_packages/lifetime.rs
  openmls/src/messages/group_info.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node.rs
  openmls/src/treesync/node/codec.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/treekem.rs
  openmls/src/versions.rs
  traits/src/types.rs
Labels: size/l

#1470 Add credentials_to_verify method to StagedCommit
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/messages/proposals.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
Labels: size/m

#1464 MlsGroup: Builder, Pattern and Config
  CHANGELOG.md
  book/src/forward_secrecy.md
  book/src/user_manual/create_group.md
  book/src/user_manual/group_config.md
  book/src/user_manual/join_from_external_commit.md
  book/src/user_manual/join_from_welcome.md
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/ser.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/test_decryption_key_index.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_interop_scenarios.rs
  openmls/tests/test_managed_api.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1473 Add `with_group_context_extensions` method to group builders
  book/src/user_manual/create_group.md
  openmls/src/extensions/errors.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/public_group/builder.rs
  openmls/tests/book_code.rs
Labels: size/m

#1475 Process GroupContextExtensions Proposals
  book/src/message_validation.md
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
Labels: size/m

#1477 Add leaf node configuration options to MlsGroup builder
  book/src/user_manual/group_config.md
  openmls/src/extensions/errors.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/builder.rs
  openmls/tests/book_code.rs
Labels: size/m

#1478 Clean up `MlsGroup*` builders
  CHANGELOG.md
  book/src/user_manual/group_config.md
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/tests/book_code.rs
Labels: size/m

#1479 Enable the use of unknown/opaque group context extensions.
  CHANGELOG.md
  book/src/user_manual/group_config.md
  openmls/src/extensions/mod.rs
  openmls/src/extensions/required_capabilities.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/test_mls_group.rs
Labels: size/m

#1483 Enable Wasm Tests
  .github/workflows/build.yml
  .github/workflows/tests.yml
  book/src/SUMMARY.md
  book/src/user_manual/wasm.md
  openmls/Cargo.toml
  openmls/src/binary_tree/array_representation/kat_treemath.rs
  openmls/src/ciphersuite/tests/kat_crypto_basics.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/kat_vl.rs
  openmls/src/key_packages/lifetime.rs
  openmls/src/lib.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/kat_psk_secret.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/tree/tests_and_kats/kats/secret_tree.rs
  openmls/src/treesync/node/parent_node.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_validation.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/src/treesync/treekem.rs
Labels: size/m
