Repository openmls/openmls, pull requests merged in 2024-04, with the labels that each got.

#1539 Further improve credentials
  cli/src/identity.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls-wasm/src/lib.rs
  openmls/benches/benchmark.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1541 Return leaf node for public staged commit states
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/public_group/staged_commit.rs
Labels: size/s

#1537 Introduce frankenstein framework
  interop_client/src/main.rs
  openmls/src/ciphersuite/signature.rs
  openmls/src/ciphersuite/tests/test_secrets.rs
  openmls/src/credentials/tests.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/frankenstein/framing.rs
  openmls/src/test_utils/frankenstein/key_package.rs
  openmls/src/test_utils/frankenstein/leaf_node.rs
  openmls/src/test_utils/frankenstein/mod.rs
  openmls/src/test_utils/mod.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/src/versions.rs
Labels: size/l

#1545 Remove cipher suite and version from Secret
  CHANGELOG.md
  interop_client/src/main.rs
  openmls/src/ciphersuite/aead.rs
  openmls/src/ciphersuite/codec.rs
  openmls/src/ciphersuite/mac.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/ciphersuite/secret.rs
  openmls/src/ciphersuite/tests.rs
  openmls/src/ciphersuite/tests/kat_crypto_basics.rs
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/ciphersuite/tests/test_secrets.rs
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/private_message_in.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/public_message_in.rs
  openmls/src/framing/test_framing.rs
  openmls/src/framing/validation.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/kat_welcome.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_external_init.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/diff.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/kat_transcript_hashes.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_encoding.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/kat_psk_secret.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
  openmls/src/schedule/unit_tests.rs
  openmls/src/tree/secret_tree.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/tree/tests_and_kats/kats/secret_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_sender_ratchet.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/tests_and_kats/kats/kat_tree_operations.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/src/treesync/treekem.rs
Labels: size/l

#1546 Add XWing-based ciphersuite
  CHANGELOG.md
  libcrux_crypto/Cargo.toml
  libcrux_crypto/src/crypto.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/test_utils/mod.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls_rust_crypto/src/provider.rs
  traits/src/types.rs
Labels: size/s

#1548 Remove CryptoConfig
  CHANGELOG.md
  cli/src/identity.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls-wasm/src/lib.rs
  openmls/benches/benchmark.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/config.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/config.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/mod.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/prelude.rs
  openmls/src/test_utils/frankenstein/key_package.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
Labels: size/l

#1555 Disable MLS++ interop on CI
  .github/workflows/interop.yml
Labels: size/s

#1553 fixup build after #1548
  .github/workflows/build.yml
  openmls/Cargo.toml
  openmls/src/binary_tree/array_representation/treemath.rs
  openmls/src/ciphersuite/secret.rs
  openmls/src/schedule/mod.rs
  openmls/src/schedule/psk.rs
Labels: size/s

#1542 Enable handling of other/unknown proposals
  CHANGELOG.md
  book/src/SUMMARY.md
  book/src/message_validation.md
  book/src/user_manual/custom_proposals.md
  openmls/src/extensions/required_capabilities.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_proposals.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/builder.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/public_group/builder.rs
  openmls/src/group/public_group/errors.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/messages/codec.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/proposals.rs
  openmls/src/messages/proposals_in.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/tests/book_code.rs
Labels: size/l

#1557 Expose getter for ext_sender_index function
  openmls/src/group/mls_group/mod.rs
Labels: size/xs

#1554 expose propose_group_context_extensions and add a function
  openmls/src/extensions/required_capabilities.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/messages/proposals.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#1563 Revert "Disable MLS++ interop on CI (#1555)"
  .github/workflows/interop.yml
Labels: size/s
