Repository openmls/openmls, pull requests merged in 2024-05, with the labels that each got.

#1570 Doc updates for storage
  book/src/traits/README.md
  book/src/traits/traits.md
  openmls/src/group/mls_group/creation.rs
  openmls/src/key_packages/errors.rs
  openmls/src/key_packages/mod.rs
  openmls/tests/key_store.rs
  openmls/tests/store.rs
  traits/src/storage.rs
Labels: size/m

#1572 Removing unused code
  openmls/src/framing/codec.rs
  openmls/src/framing/private_message.rs
  openmls/src/storage.rs
Labels: size/s

#1571 Add more frankenstein types
  openmls/src/test_utils/frankenstein/codec.rs
  openmls/src/test_utils/frankenstein/commit.rs
  openmls/src/test_utils/frankenstein/credentials.rs
  openmls/src/test_utils/frankenstein/extensions.rs
  openmls/src/test_utils/frankenstein/framing.rs
  openmls/src/test_utils/frankenstein/group_info.rs
  openmls/src/test_utils/frankenstein/key_package.rs
  openmls/src/test_utils/frankenstein/leaf_node.rs
  openmls/src/test_utils/frankenstein/mod.rs
  openmls/src/test_utils/frankenstein/proposals.rs
Labels: size/l

#1577 Return an empty vector in storage.aad when it's not found
  memory_storage/src/lib.rs
  traits/src/storage.rs
Labels: size/xs

#1578 Remove PartialEq requirement from associated Error type
  openmls/src/storage.rs
Labels: size/xs

#1579 Proposal storage update
  memory_storage/src/lib.rs
  memory_storage/src/test_store.rs
  memory_storage/tests/proposals.rs
  openmls/src/group/mls_group/mod.rs
  traits/src/storage.rs
Labels: size/m

#1582 benchmarks for ml-kem
  openmls/benches/benchmark.rs
Labels: size/m

#1581 Storage docs and small fix
  openmls/src/key_packages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  traits/src/storage.rs
Labels: size/s

#1583 Update gce staged commit test
  openmls/tests/test_mls_group.rs
  openmls_test/src/lib.rs
Labels: size/s

#1584 add changelog for new storage API
  CHANGELOG.md
Labels: size/xs
