Repository openmls/openmls, pull requests merged in 2024-11, with the labels that each got.

#1673 Feat: Better error when attempting to decrypt own messages
  CHANGELOG.md
  openmls/src/framing/validation.rs
  openmls/src/group/errors.rs
  openmls/tests/own_messages.rs
Labels: size/m

#1676 Fix docs link
  openmls/Cargo.toml
Labels: size/xs

#1679 Fixing a few typos in the book
  book/src/user_manual/credential_validation.md
  book/src/user_manual/custom_proposals.md
Labels: size/s

#1678 Update README.md ciphersuite names
  README.md
Labels: size/xs

#1683 ci: Fix coverage
  .github/workflows/coverage.yml
Labels: size/s

#1675 Add Commit Builder
  book/src/user_manual/add_members.md
  openmls/benches/benchmark.rs
  openmls/examples/large-groups.rs
  openmls/src/extensions/tests.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/tests.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/commit_builder.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/membership.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/proposal.rs
  openmls/src/group/mls_group/proposal_store.rs
  openmls/src/group/mls_group/tests_and_kats/kats/passive_client.rs
  openmls/src/group/mls_group/tests_and_kats/kats/welcome.rs
  openmls/src/group/mls_group/tests_and_kats/tests/create_commit_params.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mod.rs
  openmls/src/group/mls_group/updates.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/tests_and_kats/tests/commit_validation.rs
  openmls/src/group/tests_and_kats/tests/framing_validation.rs
  openmls/src/group/tests_and_kats/tests/group.rs
  openmls/src/group/tests_and_kats/tests/past_secrets.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
  openmls/src/group/tests_and_kats/tests/wire_format_policy.rs
  openmls/src/messages/group_info.rs
  openmls/src/schedule/psk.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/kats/kat_treekem.rs
  openmls/tests/book_code.rs
  openmls/tests/external_commit.rs
  openmls/tests/mls_group.rs
  openmls/tests/store.rs
  openmls_test/src/lib.rs
Labels: size/xl

#1684 Add validation annotations and a check
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests_and_kats/tests/group_context_extensions.rs
  openmls/src/treesync/treekem.rs
Labels: size/s

#1687 Clippy fixes
  cli/src/conversation.rs
  cli/src/user.rs
  libcrux_crypto/src/crypto.rs
  memory_storage/src/persistence.rs
  openmls/src/binary_tree/array_representation/diff.rs
  openmls/src/framing/public_message.rs
  openmls/src/group/mls_group/commit_builder.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/proposal_store.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/public_group/diff/compute_path.rs
  openmls/src/test_utils/frankenstein/framing.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/treekem.rs
  traits/src/storage.rs
Labels: size/s
