Repository openmls/openmls, pull requests merged in 2024-06, with the labels that each got.

#1587 Fix for test runner
  .github/workflows/interop.yml
Labels: size/xs

#1586 API for processed welcome
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/messages/group_info.rs
  openmls/src/messages/tests/test_welcome.rs
Labels: size/l

#1594 Another interop fix
  .github/workflows/interop.yml
Labels: size/xs

#1591 Remove Duplicate Method in Storage trait
  memory_storage/src/lib.rs
  memory_storage/src/test_store.rs
  openmls/src/group/mls_group/processing.rs
  traits/src/storage.rs
Labels: size/s

#1592 Remove partialeq constraint on storage provider error
  traits/src/storage.rs
Labels: size/xs

#1590 Add Test checking GroupContextExtensionProposal Validation: Commit contains up to one GCE Proposal
  openmls/Cargo.toml
  openmls/src/framing/mls_auth_content.rs
  openmls/src/group/core_group/new_from_welcome.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/lib.rs
  openmls/src/skip_validation.rs
  openmls/src/test_utils/frankenstein/codec.rs
  openmls/src/test_utils/frankenstein/credentials.rs
  openmls/src/test_utils/frankenstein/crypto.rs
  openmls/src/test_utils/frankenstein/extensions.rs
  openmls/src/test_utils/frankenstein/framing.rs
  openmls/src/test_utils/frankenstein/group_info.rs
  openmls/src/test_utils/frankenstein/key_package.rs
  openmls/src/test_utils/frankenstein/leaf_node.rs
  openmls/src/test_utils/frankenstein/mod.rs
Labels: size/l
