Repository openmls/openmls, pull requests merged in 2024-03, with the labels that each got.

#1530 Disable failing passive client tests
  openmls/src/group/core_group/kat_passive_client.rs
Labels: size/xs

#1528 Expose the whole tls_codec crate in prelude
  basic_credential/src/lib.rs
  cli/Cargo.toml
  cli/src/networking.rs
  cli/src/user.rs
  delivery-service/ds-lib/Cargo.toml
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds/Cargo.toml
  fuzz/fuzz_targets/key_package_decode.rs
  fuzz/fuzz_targets/mls_message_decode.rs
  fuzz/fuzz_targets/proposal_decode.rs
  fuzz/fuzz_targets/welcome_decode.rs
  openmls/src/key_packages/mod.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
  traits/src/signatures.rs
  traits/src/types.rs
Labels: size/s

#1527 Improve BasicCredential
  CHANGELOG.md
  cli/src/identity.rs
  cli/src/user.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls-wasm/src/lib.rs
  openmls/benches/benchmark.rs
  openmls/src/credentials/errors.rs
  openmls/src/credentials/mod.rs
  openmls/src/credentials/tests.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
Labels: size/m

#1531 Small API improvements
  openmls/src/framing/codec.rs
  openmls/src/framing/message_out.rs
  openmls/src/framing/public_message.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/messages/group_info.rs
Labels: size/m

#1532 Fix metadata and build profiles
  openmls-wasm/Cargo.toml
  openmls-wasm/LICENSE_MIT
Labels: size/s

#1533 Make StagedWelcome consume Welcome instead of MlsMessageIn
  CHANGELOG.md
  cli/src/user.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls-wasm/src/lib.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_framing_validation.rs
  openmls/src/group/tests/test_past_secrets.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_remove_operation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/lib.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/tests/book_code.rs
  openmls/tests/test_mls_group.rs
Labels: size/m

#1534 Re-enable KATs after KeyPackage update
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/test_vectors/passive-client-handling-commit.json
  openmls/test_vectors/passive-client-random.json
Labels: size/xl

#1535 More KATs
  openmls/test_vectors/passive-client-handling-commit.json
  openmls/test_vectors/passive-client-random.json
Labels: size/m
