Repository openmls/openmls, pull requests merged in 2024-02, with the labels that each got.

#1491 Fix validation bug
  openmls/src/extensions/required_capabilities.rs
  openmls/src/group/errors.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/treesync/node/leaf_node/capabilities.rs
Labels: size/s

#1501 Update codecov
  .github/workflows/coverage.yml
Labels: size/xs

#1495 Improve processing
  book/src/user_manual/processing.md
  cli/src/user.rs
  delivery-service/ds/src/main.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/errors.rs
  openmls/src/framing/message_in.rs
  openmls/src/framing/message_out.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/kat_welcome.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_add_proposal.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/test_wire_format_policy.rs
  openmls/src/lib.rs
  openmls/src/prelude.rs
  openmls/tests/book_code.rs
  openmls/tests/test_external_commit.rs
Labels: size/m

#1498 Remove unnecessary cloning of proposals
  openmls/src/framing/mls_auth_content.rs
  openmls/src/group/core_group/proposals.rs
Labels: size/s

#1499 Cleanup unused CoreGroup methods
  openmls/src/framing/errors.rs
  openmls/src/framing/private_message.rs
  openmls/src/framing/private_message_in.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/proposals.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/test_mls_group.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/kat_messages.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_group.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/mod.rs
Labels: size/m

#1488 Allow more credentials
  CHANGELOG.md
  Cargo.toml
  book/src/SUMMARY.md
  book/src/app_validation.md
  book/src/message_validation.md
  cli/src/identity.rs
  cli/src/user.rs
  delivery-service/ds-lib/src/lib.rs
  delivery-service/ds-lib/tests/test_codec.rs
  delivery-service/ds/src/test.rs
  interop_client/src/main.rs
  openmls/benches/benchmark.rs
  openmls/src/credentials/codec.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/external_sender_extension.rs
  openmls/src/extensions/test_extensions.rs
  openmls/src/framing/test_framing.rs
  openmls/src/group/core_group/kat_passive_client.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/process.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/public_group/process.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/group/public_group/validation.rs
  openmls/src/group/tests/external_remove_proposal.rs
  openmls/src/group/tests/test_commit_validation.rs
  openmls/src/group/tests/test_external_commit_validation.rs
  openmls/src/group/tests/test_proposal_validation.rs
  openmls/src/group/tests/utils.rs
  openmls/src/key_packages/mod.rs
  openmls/src/key_packages/test_key_packages.rs
  openmls/src/lib.rs
  openmls/src/messages/mod.rs
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/test_framework/client.rs
  openmls/src/test_utils/test_framework/mod.rs
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls/src/tree/tests_and_kats/kats/kat_message_protection.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/src/treesync/tests_and_kats/tests.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/tests/book_code.rs
  openmls/tests/key_store.rs
  openmls/tests/test_external_commit.rs
  openmls/tests/test_mls_group.rs
Labels: size/xl

#1507 Add date for 0.5.0 release to changelog
  CHANGELOG.md
Labels: size/xs

#1490 Add provider backed by libcrux
  .github/workflows/tests.yml
  Cargo.toml
  book/src/traits/traits.md
  libcrux_crypto/Cargo.toml
  libcrux_crypto/src/crypto.rs
  libcrux_crypto/src/lib.rs
  libcrux_crypto/src/rand.rs
  openmls/Cargo.toml
  openmls/src/ciphersuite/hpke.rs
  openmls/src/ciphersuite/tests/test_ciphersuite.rs
  openmls/src/extensions/external_pub_extension.rs
  openmls/src/group/core_group/mod.rs
  openmls/src/group/core_group/staged_commit.rs
  openmls/src/group/core_group/test_core_group.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/messages/tests/test_welcome.rs
  openmls/src/schedule/kat_key_schedule.rs
  openmls/src/schedule/mod.rs
  openmls/src/test_utils/mod.rs
  openmls/src/treesync/node/encryption_keys.rs
  openmls_rust_crypto/src/provider.rs
  traits/src/crypto.rs
  traits/src/types.rs
Labels: size/l
