Repository openmls/openmls, pull requests merged in 2025-03, with the labels that each got.

#1728 Disable `test_new_tree_error()` due to segfault
  openmls/src/binary_tree/tests.rs
Labels: size/xs

#1730 Single group test framework
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/single_group_test_framework/assertions.rs
  openmls/src/test_utils/single_group_test_framework/errors.rs
  openmls/src/test_utils/single_group_test_framework/mod.rs
Labels: size/l

#1735 add ability to rotate signature keys
  CHANGELOG.md
  openmls/src/group/mls_group/commit_builder.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/mls_group/updates.rs
Labels: size/m

#1731 Add Helpers for resolving forks
  .github/workflows/tests.yml
  CHANGELOG.md
  book/src/SUMMARY.md
  book/src/user_manual/fork-resolution.md
  openmls/Cargo.toml
  openmls/src/ciphersuite/kdf_label.rs
  openmls/src/framing/tests.rs
  openmls/src/group/fork_resolution/mod.rs
  openmls/src/group/fork_resolution/readd.rs
  openmls/src/group/fork_resolution/reboot.rs
  openmls/src/group/mls_group/commit_builder.rs
  openmls/src/group/mls_group/exporting.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/tests_and_kats/tests/external_init.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
  openmls/src/group/mls_group/tests_and_kats/utils.rs
  openmls/src/group/mod.rs
  openmls/src/group/tests_and_kats/tests/group.rs
  openmls/src/tree/sender_ratchet.rs
  openmls/tests/book_code_fork_resolution.rs
Labels: size/xl
