Repository openmls/openmls, pull requests merged in 2025-04, with the labels that each got.

#1739 Add validation test for valn0108
  openmls/src/group/tests_and_kats/tests/key_package_in.rs
  openmls/src/group/tests_and_kats/tests/mod.rs
Labels: size/s

#1745 bump wasm threshold to 1.7MiB
  openmls-wasm/check-size.sh
Labels: size/xs

#1744 Add validation tests for valn0104
  openmls/src/group/tests_and_kats/tests/capabilities_check.rs
  openmls/src/group/tests_and_kats/tests/mod.rs
  openmls/src/test_utils/single_group_test_framework/errors.rs
  openmls/src/test_utils/single_group_test_framework/mod.rs
Labels: size/m

#1721 Add book example for discarded welcome message
  book/src/user_manual/join_from_welcome.md
  openmls/src/test_utils/mod.rs
  openmls/src/test_utils/storage_state.rs
  openmls/tests/book_code_discard_welcome.rs
Labels: size/m

#1747 Remove `binary_tree::test_new_tree_error()` (segfault on 32-bit platforms)
  openmls/src/binary_tree/tests.rs
Labels: size/s

#1754 doc: Improve the module documentation
  openmls/src/binary_tree/array_representation/mod.rs
  openmls/src/ciphersuite/mod.rs
  openmls/src/credentials/mod.rs
  openmls/src/extensions/mod.rs
  openmls/src/framing/mod.rs
  openmls/src/key_packages/mod.rs
  openmls/src/messages/mod.rs
  openmls/src/schedule/mod.rs
Labels: size/m

#1752 return error when external sender sends commit
  openmls/src/group/mls_group/errors.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/public_group/process.rs
Labels: size/s

#1748 Add references to validation check valn0113
  openmls/src/group/public_group/validation.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/s

#1759 doc: Add external add proposal to changelog
  CHANGELOG.md
Labels: size/xs

#1758 chore: Drop stale TODOs
  openmls/src/framing/message_out.rs
  openmls/src/framing/public_message.rs
  openmls/src/framing/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/group_context.rs
  openmls/src/group/mls_group/create_commit.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/public_group/diff/apply_proposals.rs
  openmls/src/group/tests_and_kats/kats/messages.rs
  openmls/src/messages/proposals.rs
  openmls/src/schedule/mod.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/errors.rs
  openmls/src/treesync/node/leaf_node.rs
  openmls/tests/interop_scenarios.rs
Labels: size/s

#1762 chore: expose LeafNodeSource
  CHANGELOG.md
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/s

#1763 Fix list of extensions valid in a leaf node
  openmls/src/extensions/mod.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
Labels: size/s

#1760 Update libcrux provider to use pure Rust crates
  .github/workflows/tests.yml
  basic_credential/Cargo.toml
  libcrux_crypto/Cargo.toml
  libcrux_crypto/src/crypto.rs
  libcrux_crypto/src/lib.rs
  libcrux_crypto/src/rand.rs
  memory_storage/Cargo.toml
  openmls/Cargo.toml
  openmls_rust_crypto/Cargo.toml
  openmls_rust_crypto/src/provider.rs
  openmls_test/Cargo.toml
  openmls_test/src/lib.rs
  sqlite_storage/Cargo.toml
  traits/CHANGELOG.md
  traits/Cargo.toml
  traits/src/types.rs
Labels: size/l

#1724 Add book examples and tests for discarded Commits
  book/src/SUMMARY.md
  book/src/user_manual/discarding_commits.md
  openmls/src/test_utils/single_group_test_framework/assertions.rs
  openmls/src/test_utils/single_group_test_framework/mod.rs
  openmls/src/test_utils/storage_state.rs
  openmls/tests/book_code_discard_commit.rs
Labels: size/l
