Repository openmls/openmls, pull requests merged in 2025-01, with the labels that each got.

#1696 Delete .github/workflows/interop.yml
  .github/workflows/interop.yml
Labels: size/m

#1697 update dependencies
  openmls/Cargo.toml
  openmls/src/tree/tests_and_kats/kats/kat_encryption.rs
  openmls_test/Cargo.toml
Labels: size/xs

#1701 fix: use "?" instead of match statement in cli
  cli/src/user.rs
Labels: size/xs

#1702 Annotate and fix missing validation checks, including ones we hadn't catalogued before
  openmls/src/binary_tree/array_representation/tree.rs
  openmls/src/framing/codec.rs
  openmls/src/framing/validation.rs
  openmls/src/group/errors.rs
  openmls/src/group/mls_group/creation.rs
  openmls/src/group/public_group/errors.rs
  openmls/src/group/public_group/mod.rs
  openmls/src/group/public_group/staged_commit.rs
  openmls/src/storage.rs
  openmls/src/treesync/diff.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/node/leaf_node.rs
Labels: size/m

#1705 Add annotations for valn0306
  openmls/src/group/public_group/validation.rs
Labels: size/xs

#1706 Update labeler.yml
  .github/workflows/labeler.yml
Labels: size/xs

#1700 Change error in MemoryStorage and result handling in OpenMLS
  CHANGELOG.md
  memory_storage/CHANGELOG.md
  memory_storage/src/lib.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/processing.rs
  openmls/src/group/mls_group/staged_commit.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
Labels: size/s

#1713 Drop dead code in signature.rs
  openmls/src/ciphersuite/signature.rs
Labels: size/s

#1703 fix: clear update proposals when a remove proposal is present for a given leaf
  CHANGELOG.md
  openmls/src/group/mls_group/proposal_store.rs
  openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
Labels: size/m

#1682 Sqlite storage provider crate
  Cargo.toml
  openmls/Cargo.toml
  openmls/src/ciphersuite/aead.rs
  openmls/src/ciphersuite/tests_and_kats/tests.rs
  openmls/src/extensions/tests.rs
  openmls/src/group/mls_group/mod.rs
  openmls/src/group/mls_group/tests_and_kats/tests/external_init.rs
  openmls/src/group/mls_group/tests_and_kats/tests/mls_group.rs
  openmls/src/group/mls_group/tests_and_kats/tests/past_secrets.rs
  openmls/src/group/mls_group/tests_and_kats/tests/proposals.rs
  openmls/src/group/public_group/tests.rs
  openmls/src/group/tests_and_kats/tests/aad.rs
  openmls/src/group/tests_and_kats/tests/external_add_proposal.rs
  openmls/src/group/tests_and_kats/tests/external_commit_validation.rs
  openmls/src/group/tests_and_kats/tests/external_remove_proposal.rs
  openmls/src/group/tests_and_kats/tests/framing.rs
  openmls/src/group/tests_and_kats/tests/framing_validation.rs
  openmls/src/group/tests_and_kats/tests/group.rs
  openmls/src/group/tests_and_kats/tests/group_context_extensions.rs
  openmls/src/group/tests_and_kats/tests/past_secrets.rs
  openmls/src/group/tests_and_kats/tests/proposal_validation.rs
  openmls/src/group/tests_and_kats/tests/remove_operation.rs
  openmls/src/group/tests_and_kats/tests/wire_format_policy.rs
  openmls/src/key_packages/tests.rs
  openmls/src/messages/tests/codec.rs
  openmls/src/messages/tests/export_group_info.rs
  openmls/src/messages/tests/proposals.rs
  openmls/src/messages/tests/welcome.rs
  openmls/src/schedule/tests_and_kats/tests.rs
  openmls/src/test_utils/mod.rs
  openmls/src/tree/tests_and_kats/unit_tests/test_secret_tree.rs
  openmls/src/treesync/mod.rs
  openmls/src/treesync/tests_and_kats/tests/test_diff.rs
  openmls/tests/mls_group.rs
  openmls_test/Cargo.toml
  openmls_test/src/lib.rs
  sqlite_storage/CHANGELOG.md
  sqlite_storage/Cargo.toml
  sqlite_storage/README.md
  sqlite_storage/migrations/V1__initial.sql
  sqlite_storage/src/codec.rs
  sqlite_storage/src/encryption_key_pairs.rs
  sqlite_storage/src/epoch_key_pairs.rs
  sqlite_storage/src/group_data.rs
  sqlite_storage/src/key_packages.rs
  sqlite_storage/src/lib.rs
  sqlite_storage/src/own_leaf_nodes.rs
  sqlite_storage/src/proposals.rs
  sqlite_storage/src/psks.rs
  sqlite_storage/src/signature_key_pairs.rs
  sqlite_storage/src/storage_provider.rs
  sqlite_storage/src/wrappers.rs
  sqlite_storage/tests/proposals.rs
Labels: size/xl
